/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
/**
 *
 * @author fresh-fresh
 */
import java.awt.Color;
import java.awt.Font;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import BD.StmtSQL;
import codex.Codex;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin(String user, String hashPass) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        main_panel.setLayout(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(3, 1, 3, 0, new Color(158, 172, 189)));
        this.user = user;
        this.password = hashPass;
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.setTitle("Administrador");
        btn_menuPrincipal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        dashboard_panel = new javax.swing.JPanel();
        btn_usuarios = new javax.swing.JLabel();
        btn_libros = new javax.swing.JLabel();
        btn_prestamos = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        btn_devol = new javax.swing.JLabel();
        btn_adminSettings = new javax.swing.JLabel();
        windowOptions_panel = new javax.swing.JPanel();
        btn_minimizeAdmin = new javax.swing.JLabel();
        btn_exitAdmin = new javax.swing.JLabel();
        btn_menuPrincipal = new javax.swing.JLabel();
        main_menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_buscarUsuario = new javax.swing.JLabel();
        btn_buscarPrestamo = new javax.swing.JLabel();
        btn_buscarDevolucion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_buscarLibro = new javax.swing.JLabel();
        btn_registrarLibro = new javax.swing.JLabel();
        btn_registrarPrestamo = new javax.swing.JLabel();
        btn_registrarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main_panel.setBackground(new java.awt.Color(0, 0, 0));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard_panel.setBackground(new java.awt.Color(71, 91, 108));
        dashboard_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_usuarios.setBackground(new java.awt.Color(54, 71, 89));
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        btn_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_users_30px.png"))); // NOI18N
        btn_usuarios.setText("MIEMBROS");
        btn_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuarios.setOpaque(true);
        btn_usuarios.setPreferredSize(new java.awt.Dimension(34, 92));
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, 90));

        btn_libros.setBackground(new java.awt.Color(54, 71, 89));
        btn_libros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        btn_libros.setForeground(new java.awt.Color(255, 255, 255));
        btn_libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_books_35px_1.png"))); // NOI18N
        btn_libros.setText("LIBROS");
        btn_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_libros.setOpaque(true);
        btn_libros.setPreferredSize(new java.awt.Dimension(120, 92));
        btn_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_librosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_librosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_librosMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 90));

        btn_prestamos.setBackground(new java.awt.Color(54, 71, 89));
        btn_prestamos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        btn_prestamos.setForeground(new java.awt.Color(255, 255, 255));
        btn_prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_borrow_book_30px_1.png"))); // NOI18N
        btn_prestamos.setText("PRESTAMOS");
        btn_prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_prestamos.setOpaque(true);
        btn_prestamos.setPreferredSize(new java.awt.Dimension(34, 92));
        btn_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_prestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_prestamosMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, -1));

        btn_logout.setBackground(new java.awt.Color(54, 71, 89));
        btn_logout.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shutdown_30px_2.png"))); // NOI18N
        btn_logout.setText("CERRAR SESIÓN");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setOpaque(true);
        btn_logout.setPreferredSize(new java.awt.Dimension(34, 92));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 120, 90));

        btn_devol.setBackground(new java.awt.Color(54, 71, 89));
        btn_devol.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        btn_devol.setForeground(new java.awt.Color(255, 255, 255));
        btn_devol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_return_30px.png"))); // NOI18N
        btn_devol.setText("DEVOLUCIONES");
        btn_devol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_devol.setOpaque(true);
        btn_devol.setPreferredSize(new java.awt.Dimension(34, 92));
        btn_devol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_devolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_devolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_devolMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_devol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 100));

        btn_adminSettings.setBackground(new java.awt.Color(34, 51, 69));
        btn_adminSettings.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_adminSettings.setForeground(new java.awt.Color(255, 255, 255));
        btn_adminSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_administrative_tools_22px_1.png"))); // NOI18N
        btn_adminSettings.setText("Administrador");
        btn_adminSettings.setToolTipText("Configuraciones");
        btn_adminSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adminSettings.setOpaque(true);
        btn_adminSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adminSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adminSettingsMouseExited(evt);
            }
        });
        dashboard_panel.add(btn_adminSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        main_panel.add(dashboard_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 500));

        windowOptions_panel.setBackground(new java.awt.Color(54, 71, 89));
        windowOptions_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowOptions_panelMouseDragged(evt);
            }
        });
        windowOptions_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowOptions_panelMousePressed(evt);
            }
        });
        windowOptions_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimizeAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeAdmin.setToolTipText("Minimizar");
        btn_minimizeAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeAdminMouseExited(evt);
            }
        });
        windowOptions_panel.add(btn_minimizeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 20, 20));

        btn_exitAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitAdmin.setToolTipText("Cerrar");
        btn_exitAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitAdminMouseExited(evt);
            }
        });
        windowOptions_panel.add(btn_exitAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 20, 20));

        btn_menuPrincipal.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_menuPrincipal.setForeground(new java.awt.Color(215, 215, 215));
        btn_menuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_page_20px_4.png"))); // NOI18N
        btn_menuPrincipal.setText("Menú principal");
        btn_menuPrincipal.setToolTipText("Ir a menú principal");
        btn_menuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuPrincipalMouseExited(evt);
            }
        });
        windowOptions_panel.add(btn_menuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        main_panel.add(windowOptions_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 630, 40));

        main_menu.setBackground(new java.awt.Color(101, 121, 146));

        jPanel1.setBackground(new java.awt.Color(61, 81, 106));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 161, 186), 2, true));

        jLabel1.setBackground(new java.awt.Color(101, 121, 146));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_books_70px_3.png"))); // NOI18N
        jLabel1.setText(">> Biblioteca Codex  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(61, 81, 106));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 161, 186), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opciones principales:");

        jPanel3.setBackground(new java.awt.Color(51, 71, 96));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 161, 186)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Otras opciones:");

        btn_buscarUsuario.setBackground(new java.awt.Color(50, 50, 50));
        btn_buscarUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_buscarUsuario.setForeground(new java.awt.Color(230, 230, 230));
        btn_buscarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_contacts_25px_1.png"))); // NOI18N
        btn_buscarUsuario.setText("Buscar miembro");
        btn_buscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarUsuario.setOpaque(true);
        btn_buscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarUsuarioMouseExited(evt);
            }
        });

        btn_buscarPrestamo.setBackground(new java.awt.Color(50, 50, 50));
        btn_buscarPrestamo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_buscarPrestamo.setForeground(new java.awt.Color(230, 230, 230));
        btn_buscarPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_buscarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_reading_25px.png"))); // NOI18N
        btn_buscarPrestamo.setText("Consultar préstamo");
        btn_buscarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarPrestamo.setOpaque(true);
        btn_buscarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarPrestamoMouseExited(evt);
            }
        });

        btn_buscarDevolucion.setBackground(new java.awt.Color(50, 50, 50));
        btn_buscarDevolucion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_buscarDevolucion.setForeground(new java.awt.Color(230, 230, 230));
        btn_buscarDevolucion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_buscarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_return_25px.png"))); // NOI18N
        btn_buscarDevolucion.setText("Consultar Devolución");
        btn_buscarDevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarDevolucion.setOpaque(true);
        btn_buscarDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarDevolucionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarDevolucionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarDevolucionMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_info_15px.png"))); // NOI18N
        jLabel11.setToolTipText("Para más opciones ir al menú de la izquierda.");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_buscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_buscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_buscarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btn_buscarLibro.setBackground(new java.awt.Color(210, 210, 210));
        btn_buscarLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        btn_buscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_property_50px.png"))); // NOI18N
        btn_buscarLibro.setText("Buscar libro");
        btn_buscarLibro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_buscarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarLibro.setOpaque(true);
        btn_buscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarLibroMouseExited(evt);
            }
        });

        btn_registrarLibro.setBackground(new java.awt.Color(210, 210, 210));
        btn_registrarLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        btn_registrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_books_50px_1.png"))); // NOI18N
        btn_registrarLibro.setText("Registrar libro");
        btn_registrarLibro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_registrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarLibro.setOpaque(true);
        btn_registrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseExited(evt);
            }
        });

        btn_registrarPrestamo.setBackground(new java.awt.Color(210, 210, 210));
        btn_registrarPrestamo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        btn_registrarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_order_history_50px.png"))); // NOI18N
        btn_registrarPrestamo.setText("Registrar préstamo");
        btn_registrarPrestamo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_registrarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarPrestamo.setOpaque(true);
        btn_registrarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseExited(evt);
            }
        });

        btn_registrarUsuario.setBackground(new java.awt.Color(210, 210, 210));
        btn_registrarUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        btn_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_male_user_50px.png"))); // NOI18N
        btn_registrarUsuario.setText("Registrar miembro");
        btn_registrarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_registrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarUsuario.setOpaque(true);
        btn_registrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscarLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_registrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(main_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 630, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_minimizeAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeAdminMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeAdminMouseClicked

    private void windowOptions_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowOptions_panelMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_windowOptions_panelMousePressed

    private void windowOptions_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowOptions_panelMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_windowOptions_panelMouseDragged

    private void btn_exitAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitAdminMouseClicked
        try {
            if(pLibros!=null)
                cxn.cerrarConexion();
        } catch (SQLException ex) {
        }
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btn_exitAdminMouseClicked

    private void btn_exitAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitAdminMouseEntered
        btn_exitAdmin.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitAdminMouseEntered

    private void btn_exitAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitAdminMouseExited
        btn_exitAdmin.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitAdminMouseExited

    private void btn_minimizeAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeAdminMouseEntered
        btn_minimizeAdmin.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeAdminMouseEntered

    private void btn_minimizeAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeAdminMouseExited
        btn_minimizeAdmin.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeAdminMouseExited

    private void btn_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseClicked
        clickDash = 1;
        returnPreButtonStyle(btn_libros, "../icons/icons8_books_40px_3.png","Segoe UI Semilight", 2, 13);
        btn_libros.setBackground(new Color(101,121,146));
        returnPreButtonStyle(btn_prestamos, "../icons/icons8_borrow_book_30px_1.png","Segoe UI Semilight", 0, 11);
        btn_prestamos.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_devol, "../icons/icons8_return_30px.png","Segoe UI Semilight", 0, 11);
        btn_devol.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_usuarios, "../icons/icons8_users_30px.png","Segoe UI Semilight", 0, 11);
        btn_usuarios.setBackground(new Color(54,71,89));
        if(pLibros==null){
            pLibros = new Libros(cxn);
            main_panel.add(pLibros);
            pLibros.setLocation(120,40);
        }
        if(pPrestamos!=null)
            pPrestamos.setVisible(false);
        if(pDevoluciones!=null)
            pDevoluciones.setVisible(false);
        if(pMiembros!=null)
            pMiembros.setVisible(false);
        main_menu.setVisible(false);
        pLibros.setVisible(true);
        btn_menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_librosMouseClicked

    private void btn_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamosMouseClicked
        clickDash = 2;
        returnPreButtonStyle(btn_prestamos, "../icons/icons8_borrow_book_40px_1.png","Segoe UI Semilight", 2, 13);
        btn_prestamos.setBackground(new Color(101,121,146));
        returnPreButtonStyle(btn_libros, "../icons/icons8_books_35px_1.png","Segoe UI Semilight", 0, 11);
        btn_libros.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_devol, "../icons/icons8_return_30px.png","Segoe UI Semilight", 0, 11);
        btn_devol.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_usuarios, "../icons/icons8_users_30px.png","Segoe UI Semilight", 0, 11);
        btn_usuarios.setBackground(new Color(54,71,89));
        if(pPrestamos==null){
            pPrestamos = new Prestamos(cxn);
            main_panel.add(pPrestamos);
            pPrestamos.setLocation(120,40);
        }
        if(pLibros!=null)
            pLibros.setVisible(false);
        if(pDevoluciones!=null)
            pDevoluciones.setVisible(false);
        if(pMiembros!=null)
            pMiembros.setVisible(false);
        main_menu.setVisible(false);
        pPrestamos.setVisible(true);
        btn_menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_prestamosMouseClicked

    private void btn_devolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolMouseClicked
        clickDash = 3;
        returnPreButtonStyle(btn_devol, "../icons/icons8_return_40px.png","Segoe UI Semilight", 2, 11);
        btn_devol.setBackground(new Color(101,121,146));
        returnPreButtonStyle(btn_prestamos, "../icons/icons8_borrow_book_30px_1.png","Segoe UI Semilight", 0, 11);
        btn_prestamos.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_libros, "../icons/icons8_books_35px_1.png","Segoe UI Semilight", 0, 11);
        btn_libros.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_usuarios, "../icons/icons8_users_30px.png","Segoe UI Semilight", 0, 11);
        btn_usuarios.setBackground(new Color(54,71,89));
        if(pDevoluciones==null){
            pDevoluciones = new Devoluciones(cxn);
            main_panel.add(pDevoluciones);
            pDevoluciones.setLocation(120,40);
        }
        if(pLibros!=null)
            pLibros.setVisible(false);
        if(pPrestamos!=null)
            pPrestamos.setVisible(false);
        if(pMiembros!=null)
            pMiembros.setVisible(false);
        main_menu.setVisible(false);
        pDevoluciones.setVisible(true);
        btn_menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_devolMouseClicked

    private void btn_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseClicked
        clickDash = 4;
        returnPreButtonStyle(btn_usuarios, "../icons/icons8_users_40px.png","Segoe UI Semilight", 2, 13);
        btn_usuarios.setBackground(new Color(101,121,146));
        returnPreButtonStyle(btn_prestamos, "../icons/icons8_borrow_book_30px_1.png","Segoe UI Semilight", 0, 11);
        btn_prestamos.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_devol, "../icons/icons8_return_30px.png","Segoe UI Semilight", 0, 11);
        btn_devol.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_libros, "../icons/icons8_books_35px_1.png","Segoe UI Semilight", 0, 11);
        btn_libros.setBackground(new Color(54,71,89));
        if(pMiembros==null){
            pMiembros = new Miembros(cxn);
            main_panel.add(pMiembros);
            pMiembros.setLocation(120,40);
        }
        if(pLibros!=null)
            pLibros.setVisible(false);
        if(pPrestamos!=null)
            pPrestamos.setVisible(false);
        if(pDevoluciones!=null)
            pDevoluciones.setVisible(false);
        main_menu.setVisible(false);
        pMiembros.setVisible(true);
        btn_menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_usuariosMouseClicked

    private void returnPreButtonStyle(javax.swing.JLabel btn, String filename, String font, int styleFont, int textSize){
        btn.setIcon(new ImageIcon(this.getClass().getResource(filename)));
        btn.setFont(new Font(font, styleFont, textSize));
    }
    
    
    private void btn_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseEntered
        if(clickDash != 1)
            btn_libros.setBackground(new Color(81,101,118));
    }//GEN-LAST:event_btn_librosMouseEntered

    private void btn_prestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamosMouseEntered
        if(clickDash != 2)
         btn_prestamos.setBackground(new Color(81,101,118));
    }//GEN-LAST:event_btn_prestamosMouseEntered

    private void btn_devolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolMouseEntered
        if(clickDash != 3)
            btn_devol.setBackground(new Color(81,101,118));
    }//GEN-LAST:event_btn_devolMouseEntered

    private void btn_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseEntered
        if(clickDash != 4)
            btn_usuarios.setBackground(new Color(81,101,118));
    }//GEN-LAST:event_btn_usuariosMouseEntered

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        btn_logout.setBackground(new Color(81,101,118));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_librosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseExited
        if(clickDash != 1)
            btn_libros.setBackground(new Color(54,71,89));
    }//GEN-LAST:event_btn_librosMouseExited

    private void btn_prestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamosMouseExited
        if(clickDash != 2)
            btn_prestamos.setBackground(new Color(54,71,89));
    }//GEN-LAST:event_btn_prestamosMouseExited

    private void btn_devolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolMouseExited
        if(clickDash != 3)
            btn_devol.setBackground(new Color(54,71,89));
    }//GEN-LAST:event_btn_devolMouseExited

    private void btn_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseExited
        if(clickDash != 4)
            btn_usuarios.setBackground(new Color(54,71,89));
    }//GEN-LAST:event_btn_usuariosMouseExited

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        btn_logout.setBackground(new Color(54,71,89));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_adminSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminSettingsMouseEntered
        returnPreButtonStyle(btn_adminSettings, "../icons/icons8_administrative_tools_22px_2.png", "Segoe UI Semilight", 0, 15);
    }//GEN-LAST:event_btn_adminSettingsMouseEntered

    private void btn_adminSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminSettingsMouseExited
        returnPreButtonStyle(btn_adminSettings, "../icons/icons8_administrative_tools_22px_1.png", "Segoe UI Semilight", 0, 14);
    }//GEN-LAST:event_btn_adminSettingsMouseExited

    private void btn_adminSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminSettingsMouseClicked
        if(pConfigAdmin == null){
            pConfigAdmin = new ConfiguracionesAdmin(user, password);
            pConfigAdmin.setVisible(true);
        }
        pConfigAdmin.setVisible(true);
    }//GEN-LAST:event_btn_adminSettingsMouseClicked

    private void btn_buscarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarLibroMouseEntered
        returnPreButtonStyle(btn_buscarLibro, "../icons/icons8_search_property_55px.png", "Segoe UI Semilight", 0, 18);
        btn_buscarLibro.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_btn_buscarLibroMouseEntered

    private void btn_buscarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarLibroMouseExited
        returnPreButtonStyle(btn_buscarLibro, "../icons/icons8_search_property_50px.png", "Segoe UI Semilight", 0, 17);
        btn_buscarLibro.setBackground(new Color(210,210,210));
    }//GEN-LAST:event_btn_buscarLibroMouseExited

    private void btn_registrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseEntered
        returnPreButtonStyle(btn_registrarLibro, "../icons/icons8_books_55px_1.png", "Segoe UI Semilight", 0, 18);
        btn_registrarLibro.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarLibroMouseEntered

    private void btn_registrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseEntered
        returnPreButtonStyle(btn_registrarUsuario, "../icons/icons8_add_male_user_55px.png", "Segoe UI Semilight", 0, 18);
        btn_registrarUsuario.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarUsuarioMouseEntered

    private void btn_registrarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseEntered
        returnPreButtonStyle(btn_registrarPrestamo, "../icons/icons8_order_history_55px.png", "Segoe UI Semilight", 0, 18);
        btn_registrarPrestamo.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarPrestamoMouseEntered

    private void btn_registrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseExited
        returnPreButtonStyle(btn_registrarLibro, "../icons/icons8_books_50px_1.png", "Segoe UI Semilight", 0, 17);
        btn_registrarLibro.setBackground(new Color(210,210,210));
    }//GEN-LAST:event_btn_registrarLibroMouseExited

    private void btn_registrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseExited
        returnPreButtonStyle(btn_registrarUsuario, "../icons/icons8_add_male_user_50px.png", "Segoe UI Semilight", 0, 17);
        btn_registrarUsuario.setBackground(new Color(210,210,210));
    }//GEN-LAST:event_btn_registrarUsuarioMouseExited

    private void btn_registrarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseExited
        returnPreButtonStyle(btn_registrarPrestamo, "../icons/icons8_order_history_50px.png", "Segoe UI Semilight", 0, 17);
        btn_registrarPrestamo.setBackground(new Color(210,210,210));
    }//GEN-LAST:event_btn_registrarPrestamoMouseExited

    private void btn_buscarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioMouseEntered
        btn_buscarUsuario.setBackground(new Color(70,70,70));
        btn_buscarUsuario.setForeground(new Color(255,255,255));
        btn_buscarUsuario.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_contacts_25px_2.png")));
    }//GEN-LAST:event_btn_buscarUsuarioMouseEntered

    private void btn_buscarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarPrestamoMouseEntered
        btn_buscarPrestamo.setBackground(new Color(70,70,70));
        btn_buscarPrestamo.setForeground(new Color(255,255,255));
        btn_buscarPrestamo.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_book_reading_25px_1.png")));
    }//GEN-LAST:event_btn_buscarPrestamoMouseEntered

    private void btn_buscarDevolucionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarDevolucionMouseEntered
        btn_buscarDevolucion.setBackground(new Color(70,70,70));
        btn_buscarDevolucion.setForeground(new Color(255,255,255));
        btn_buscarDevolucion.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_return_25px_1.png")));
    }//GEN-LAST:event_btn_buscarDevolucionMouseEntered

    private void btn_buscarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioMouseExited
        btn_buscarUsuario.setBackground(new Color(50,50,50));
        btn_buscarUsuario.setForeground(new Color(230,230,230));
        btn_buscarUsuario.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_contacts_25px_1.png")));
    }//GEN-LAST:event_btn_buscarUsuarioMouseExited

    private void btn_buscarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarPrestamoMouseExited
        btn_buscarPrestamo.setBackground(new Color(50,50,50));
        btn_buscarPrestamo.setForeground(new Color(230,230,230));
        btn_buscarPrestamo.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_book_reading_25px.png")));
    }//GEN-LAST:event_btn_buscarPrestamoMouseExited

    private void btn_buscarDevolucionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarDevolucionMouseExited
        btn_buscarDevolucion.setBackground(new Color(50,50,50));
        btn_buscarDevolucion.setForeground(new Color(230,230,230));
        btn_buscarDevolucion.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_return_25px.png")));
    }//GEN-LAST:event_btn_buscarDevolucionMouseExited

    private void btn_buscarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarLibroMouseClicked
        btn_librosMouseClicked(null);
    }//GEN-LAST:event_btn_buscarLibroMouseClicked

    private void btn_registrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseClicked
        if(vRegistrarLibro==null){
            vRegistrarLibro = new RegistrarLibro(cxn);
            vRegistrarLibro.setVisible(true);
        }else{
            vRegistrarLibro.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarLibroMouseClicked

    private void btn_registrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseClicked
        if(vRegistrarUsuario==null){
            vRegistrarUsuario = new RegistrarMiembro(cxn);
            vRegistrarUsuario.setVisible(true);
        }else{
            vRegistrarUsuario.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarUsuarioMouseClicked

    private void btn_registrarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseClicked
        if(vRegistrarPrestamo==null){
            vRegistrarPrestamo = new RegistrarPrestamo(cxn);
            vRegistrarPrestamo.setVisible(true);
        }else{
            vRegistrarPrestamo.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarPrestamoMouseClicked

    private void btn_buscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioMouseClicked
        btn_usuariosMouseClicked(null);
    }//GEN-LAST:event_btn_buscarUsuarioMouseClicked

    private void btn_buscarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarPrestamoMouseClicked
        btn_prestamosMouseClicked(null);
    }//GEN-LAST:event_btn_buscarPrestamoMouseClicked

    private void btn_buscarDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarDevolucionMouseClicked
        btn_devolMouseClicked(null);
    }//GEN-LAST:event_btn_buscarDevolucionMouseClicked

    private void btn_menuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuPrincipalMouseEntered
        btn_menuPrincipal.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_home_page_20px_1.png")));
        btn_menuPrincipal.setForeground(new Color(250,250,250));
    }//GEN-LAST:event_btn_menuPrincipalMouseEntered

    private void btn_menuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuPrincipalMouseExited
        btn_menuPrincipal.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_home_page_20px_4.png")));
        btn_menuPrincipal.setForeground(new Color(215,215,215));
    }//GEN-LAST:event_btn_menuPrincipalMouseExited

    private void btn_menuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuPrincipalMouseClicked
        clickDash = 0;
        returnPreButtonStyle(btn_usuarios, "../icons/icons8_users_30px.png","Segoe UI Semilight", 0, 11);
        btn_usuarios.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_prestamos, "../icons/icons8_borrow_book_30px_1.png","Segoe UI Semilight", 0, 11);
        btn_prestamos.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_devol, "../icons/icons8_return_30px.png","Segoe UI Semilight", 0, 11);
        btn_devol.setBackground(new Color(54,71,89));
        returnPreButtonStyle(btn_libros, "../icons/icons8_books_35px_1.png","Segoe UI Semilight", 0, 11);
        btn_libros.setBackground(new Color(54,71,89));
        if(pMiembros!=null)
            pMiembros.setVisible(false);
        if(pLibros!=null)
            pLibros.setVisible(false);
        if(pPrestamos!=null)
            pPrestamos.setVisible(false);
        if(pDevoluciones!=null)
            pDevoluciones.setVisible(false);
        btn_menuPrincipal.setVisible(false);
        main_menu.setVisible(true);
    }//GEN-LAST:event_btn_menuPrincipalMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        try {
            if(pLibros!=null)
                cxn.cerrarConexion();
        } catch (SQLException ex) {
        }
        this.dispose();
        Codex l = new Codex();
        l.setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adminSettings;
    private javax.swing.JLabel btn_buscarDevolucion;
    private javax.swing.JLabel btn_buscarLibro;
    private javax.swing.JLabel btn_buscarPrestamo;
    private javax.swing.JLabel btn_buscarUsuario;
    private javax.swing.JLabel btn_devol;
    private javax.swing.JLabel btn_exitAdmin;
    private javax.swing.JLabel btn_libros;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_menuPrincipal;
    private javax.swing.JLabel btn_minimizeAdmin;
    private javax.swing.JLabel btn_prestamos;
    private javax.swing.JLabel btn_registrarLibro;
    private javax.swing.JLabel btn_registrarPrestamo;
    private javax.swing.JLabel btn_registrarUsuario;
    private javax.swing.JLabel btn_usuarios;
    private javax.swing.JPanel dashboard_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel main_menu;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel windowOptions_panel;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    private int clickDash = 0;
    private Libros pLibros;
    private Prestamos pPrestamos;
    private Devoluciones pDevoluciones;
    private Miembros pMiembros;
    private ConfiguracionesAdmin pConfigAdmin;
    private RegistrarMiembro vRegistrarUsuario;
    private RegistrarPrestamo vRegistrarPrestamo;
    private RegistrarLibro vRegistrarLibro;
    private final StmtSQL cxn = new StmtSQL();
    String user;
    String password;
}
