/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.CambiarDatosAdmin;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author fresh-fresh
 */
public class ConfiguracionesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarLibro
     */
    public ConfiguracionesAdmin(String user, String password) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.user = user;
        this.password = password;
        this.setTitle("Configuracion de Adminitrador");
        new TextPrompt("  Usuario", txtf_admin); 
        new TextPrompt("  Nueva Contraseña", txtf_adminPassword);
        new TextPrompt("  Confirmar Contraseña", txtf_adminConfirmPassword);
        txtf_admin.setText(user);
        txtf_adminPassword.setText("");
        txtf_adminConfirmPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        main_panelConfigAdmin = new javax.swing.JPanel();
        panel_windowOpRegistroLibro = new javax.swing.JPanel();
        btn_exitRegistrarLibro = new javax.swing.JLabel();
        btn_minimizeRegistrarLibro = new javax.swing.JLabel();
        lbl_titleConfigAdmin = new javax.swing.JLabel();
        panel_formulario = new javax.swing.JPanel();
        jseparator = new javax.swing.JSeparator();
        txtf_admin = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtf_adminPassword = new javax.swing.JPasswordField();
        jseparator2 = new javax.swing.JSeparator();
        txtf_adminConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(348, 330));

        main_panelConfigAdmin.setBackground(new java.awt.Color(71, 91, 116));
        main_panelConfigAdmin.setPreferredSize(new java.awt.Dimension(348, 330));
        main_panelConfigAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_windowOpRegistroLibro.setBackground(new java.awt.Color(41, 61, 86));
        panel_windowOpRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 30));
        panel_windowOpRegistroLibro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMouseDragged(evt);
            }
        });
        panel_windowOpRegistroLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMousePressed(evt);
            }
        });

        btn_exitRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitRegistrarLibro.setToolTipText("Cerrar");
        btn_exitRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseExited(evt);
            }
        });

        btn_minimizeRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeRegistrarLibro.setToolTipText("Minimizar");
        btn_minimizeRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_windowOpRegistroLibroLayout = new javax.swing.GroupLayout(panel_windowOpRegistroLibro);
        panel_windowOpRegistroLibro.setLayout(panel_windowOpRegistroLibroLayout);
        panel_windowOpRegistroLibroLayout.setHorizontalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_windowOpRegistroLibroLayout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(btn_minimizeRegistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exitRegistrarLibro)
                .addContainerGap())
        );
        panel_windowOpRegistroLibroLayout.setVerticalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_minimizeRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(btn_exitRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panelConfigAdmin.add(panel_windowOpRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        lbl_titleConfigAdmin.setBackground(new java.awt.Color(51, 71, 96));
        lbl_titleConfigAdmin.setFont(new java.awt.Font("Kristen ITC", 0, 15)); // NOI18N
        lbl_titleConfigAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titleConfigAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_administrative_tools_25px.png"))); // NOI18N
        lbl_titleConfigAdmin.setText("Configuraciones de Administrador");
        lbl_titleConfigAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 121, 146), 2, true));
        lbl_titleConfigAdmin.setOpaque(true);
        main_panelConfigAdmin.add(lbl_titleConfigAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 30));

        panel_formulario.setBackground(new java.awt.Color(51, 71, 96));
        panel_formulario.setPreferredSize(new java.awt.Dimension(348, 250));

        jseparator.setBackground(new java.awt.Color(131, 151, 176));
        jseparator.setForeground(new java.awt.Color(0, 0, 0));

        txtf_admin.setBackground(new java.awt.Color(51, 71, 96));
        txtf_admin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_admin.setForeground(new java.awt.Color(255, 255, 255));
        txtf_admin.setBorder(null);
        txtf_admin.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_admin.setOpaque(false);
        txtf_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_adminKeyTyped(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_17px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_17px.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txtf_adminPassword.setBackground(new java.awt.Color(51, 71, 96));
        txtf_adminPassword.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_adminPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtf_adminPassword.setBorder(null);
        txtf_adminPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_adminPasswordKeyTyped(evt);
            }
        });

        txtf_adminConfirmPassword.setBackground(new java.awt.Color(51, 71, 96));
        txtf_adminConfirmPassword.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_adminConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtf_adminConfirmPassword.setBorder(null);
        txtf_adminConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_adminConfirmPasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_formularioLayout = new javax.swing.GroupLayout(panel_formulario);
        panel_formulario.setLayout(panel_formularioLayout);
        panel_formularioLayout.setHorizontalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jseparator)
                    .addComponent(txtf_admin)
                    .addComponent(jSeparator1)
                    .addComponent(txtf_adminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jseparator2)
                    .addComponent(txtf_adminConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_formularioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addGap(26, 26, 26)
                .addComponent(btn_cancelar)
                .addGap(63, 63, 63))
        );
        panel_formularioLayout.setVerticalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jseparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtf_adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtf_adminConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jseparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar))
                .addGap(31, 31, 31))
        );

        main_panelConfigAdmin.add(panel_formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 348, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelConfigAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelConfigAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseClicked

    private void btn_exitRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseEntered
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseEntered

    private void btn_exitRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseExited
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseExited

    private void btn_minimizeRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseClicked

    private void btn_minimizeRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseEntered
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseEntered

    private void btn_minimizeRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseExited
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseExited

    private void panel_windowOpRegistroLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_windowOpRegistroLibroMousePressed

    private void panel_windowOpRegistroLibroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_panel_windowOpRegistroLibroMouseDragged

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txtf_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_adminKeyTyped
        if(txtf_admin.getText().length() >= 25)
            evt.consume();
    }//GEN-LAST:event_txtf_adminKeyTyped

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void txtf_adminPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_adminPasswordKeyTyped
        if(txtf_adminPassword.getText().length() >= 25)
            evt.consume();
    }//GEN-LAST:event_txtf_adminPasswordKeyTyped

    private String generarHash(byte[] stringBytes, String algoritmo){
        String hash = "";
        try{
            MessageDigest md = MessageDigest.getInstance(algoritmo);
            md.update(stringBytes);
            byte[] rsBytes = md.digest();
            hash = DatatypeConverter.printHexBinary(rsBytes).toLowerCase();
        }catch(NoSuchAlgorithmException e){
            e.printStackTrace(System.out);
        }
        return hash;
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String confirm = JOptionPane.showInputDialog(null,"Escribe la contraseña actual para confirmar: ", "Codex", 1);
        if(txtf_adminPassword.getText() != "" && txtf_adminPassword.getText().equals(txtf_adminConfirmPassword.getText()) && password.equals(generarHash(confirm.getBytes(),"md5"))){
            String nPassword = generarHash(txtf_adminPassword.getText().getBytes(),"md5");
            String nUser = txtf_admin.getText();
            try {
                cAdmin.actualizarAdmin(user,nUser, nPassword);
                txtf_admin.setText(nUser);
                JOptionPane.showMessageDialog(null, "Se ha Actulizado Correctamente.","Codex",1);
            } catch (SQLException ex) {
                txtf_admin.setText(user);
                JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage(),"Codex",2);
            }
        }else{
            txtf_admin.setText(user);
            JOptionPane.showMessageDialog(null, "ERROR: datos incorrectos","Codex",2);
        }    
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtf_adminConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_adminConfirmPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_adminConfirmPasswordKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel btn_exitRegistrarLibro;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel btn_minimizeRegistrarLibro;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jseparator;
    private javax.swing.JSeparator jseparator2;
    private javax.swing.JLabel lbl_titleConfigAdmin;
    private javax.swing.JPanel main_panelConfigAdmin;
    private javax.swing.JPanel panel_formulario;
    private javax.swing.JPanel panel_windowOpRegistroLibro;
    private javax.swing.JTextField txtf_admin;
    private javax.swing.JPasswordField txtf_adminConfirmPassword;
    private javax.swing.JPasswordField txtf_adminPassword;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    String user;
    String password;
    CambiarDatosAdmin cAdmin = new CambiarDatosAdmin();
}
