/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import BD.StmtSQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author fresh-fresh
 */
public final class Libros extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     * @param cxn
     */
    public Libros(StmtSQL cxn) {
        initComponents();
        setSize(630,460);
        new TextPrompt("   Buscar Libro... ", txtf_buscadorLibro);
        this.cxn = cxn;
        configTable();
        setTableData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_buscadorLibro = new javax.swing.JPanel();
        txtf_buscadorLibro = new javax.swing.JTextField();
        btn_buscarLibro = new javax.swing.JLabel();
        cmb_ordenar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_libros = new javax.swing.JTable();
        panel_opcionesBtnLibros = new javax.swing.JPanel();
        btn_registrarLibro = new javax.swing.JLabel();
        btn_modificarLibro = new javax.swing.JLabel();
        btn_eliminarLibro = new javax.swing.JLabel();
        lbl_opciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(101, 121, 146));
        setPreferredSize(new java.awt.Dimension(630, 460));

        panel_buscadorLibro.setBackground(new java.awt.Color(71, 91, 116));

        txtf_buscadorLibro.setBackground(new java.awt.Color(161, 181, 206));
        txtf_buscadorLibro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtf_buscadorLibro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_buscadorLibro.setToolTipText("Buscar por titulo, autor, editorial o ISBN.");
        txtf_buscadorLibro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtf_buscadorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_buscadorLibroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_buscadorLibroKeyTyped(evt);
            }
        });

        btn_buscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px_3.png"))); // NOI18N
        btn_buscarLibro.setToolTipText("Buscar");
        btn_buscarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarLibroMouseExited(evt);
            }
        });

        cmb_ordenar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cmb_ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por", "Titulo", "Nombre Autor", "ISBN", "No. paginas" }));

        javax.swing.GroupLayout panel_buscadorLibroLayout = new javax.swing.GroupLayout(panel_buscadorLibro);
        panel_buscadorLibro.setLayout(panel_buscadorLibroLayout);
        panel_buscadorLibroLayout.setHorizontalGroup(
            panel_buscadorLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buscadorLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtf_buscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_buscadorLibroLayout.setVerticalGroup(
            panel_buscadorLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_buscadorLibroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_buscadorLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_buscadorLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtf_buscadorLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscarLibro, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N

        table_libros.setBackground(new java.awt.Color(161, 181, 206));
        table_libros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        table_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_libros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table_libros);
        if (table_libros.getColumnModel().getColumnCount() > 0) {
            table_libros.getColumnModel().getColumn(0).setPreferredWidth(10);
            table_libros.getColumnModel().getColumn(0).setMaxWidth(5);
            table_libros.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_libros.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_libros.getColumnModel().getColumn(3).setPreferredWidth(60);
            table_libros.getColumnModel().getColumn(4).setPreferredWidth(2);
            table_libros.getColumnModel().getColumn(5).setPreferredWidth(5);
            table_libros.getColumnModel().getColumn(6).setPreferredWidth(5);
            table_libros.getColumnModel().getColumn(7).setPreferredWidth(6);
            table_libros.getColumnModel().getColumn(8).setPreferredWidth(2);
            table_libros.getColumnModel().getColumn(9).setPreferredWidth(2);
            table_libros.getColumnModel().getColumn(10).setPreferredWidth(5);
            table_libros.getColumnModel().getColumn(11).setPreferredWidth(5);
        }

        panel_opcionesBtnLibros.setBackground(new java.awt.Color(71, 91, 116));

        btn_registrarLibro.setBackground(new java.awt.Color(230, 230, 230));
        btn_registrarLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_registrarLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_books_30px.png"))); // NOI18N
        btn_registrarLibro.setText("Registrar");
        btn_registrarLibro.setToolTipText("Registrar nuevo libro.");
        btn_registrarLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_registrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarLibro.setOpaque(true);
        btn_registrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_registrarLibroMouseReleased(evt);
            }
        });

        btn_modificarLibro.setBackground(new java.awt.Color(230, 230, 230));
        btn_modificarLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_modificarLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_and_pencil_30px.png"))); // NOI18N
        btn_modificarLibro.setText("Modificar");
        btn_modificarLibro.setToolTipText("Modificar libro registrado.");
        btn_modificarLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_modificarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificarLibro.setOpaque(true);
        btn_modificarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarLibroMouseExited(evt);
            }
        });

        btn_eliminarLibro.setBackground(new java.awt.Color(230, 230, 230));
        btn_eliminarLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_eliminarLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_30px.png"))); // NOI18N
        btn_eliminarLibro.setText("Eliminar");
        btn_eliminarLibro.setToolTipText("Eliminar registro de libro.");
        btn_eliminarLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_eliminarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminarLibro.setOpaque(true);
        btn_eliminarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMouseExited(evt);
            }
        });

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setText("Opciones:");

        javax.swing.GroupLayout panel_opcionesBtnLibrosLayout = new javax.swing.GroupLayout(panel_opcionesBtnLibros);
        panel_opcionesBtnLibros.setLayout(panel_opcionesBtnLibrosLayout);
        panel_opcionesBtnLibrosLayout.setHorizontalGroup(
            panel_opcionesBtnLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_opcionesBtnLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btn_registrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_opcionesBtnLibrosLayout.setVerticalGroup(
            panel_opcionesBtnLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnLibrosLayout.createSequentialGroup()
                .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btn_registrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_opcionesBtnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_buscadorLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_buscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_opcionesBtnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void configTable(){
        model.addColumn("ID");
        model.addColumn("TITULO");
        model.addColumn("AUTOR");
        model.addColumn("EDITORIAL");
        model.addColumn("PAGINAS");
        model.addColumn("LUGAR_PUBLICACION");
        model.addColumn("ANO_PUBLICACION");
        model.addColumn("ISBN");
        model.addColumn("EXISTENCIA");
        model.addColumn("DISPONIBILIDAD");
        model.addColumn("FECHA_REGISTRO");
        model.addColumn("FECHA_BAJA");
        table_libros.setModel(model);
        TableColumnModel columnModel = table_libros.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(35);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(110);
        columnModel.getColumn(3).setPreferredWidth(110);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(140);
        columnModel.getColumn(6).setPreferredWidth(140);
        columnModel.getColumn(7).setPreferredWidth(110);
        columnModel.getColumn(8).setPreferredWidth(85);
        columnModel.getColumn(9).setPreferredWidth(110);
        columnModel.getColumn(10).setPreferredWidth(130);
        columnModel.getColumn(11).setPreferredWidth(110);
    }
    
    private void returnPreButtonStyle(javax.swing.JLabel btn, String filename, String font, int styleFont, int textSize, Color col){
        btn.setIcon(new ImageIcon(this.getClass().getResource(filename)));
        btn.setFont(new Font(font, styleFont, textSize));
        btn.setBackground(col);
    }
    
    private void btn_registrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseEntered
        returnPreButtonStyle(btn_registrarLibro, "../icons/icons8_books_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_registrarLibroMouseEntered

    private void btn_registrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseExited
        returnPreButtonStyle(btn_registrarLibro, "../icons/icons8_books_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarLibroMouseExited

    private void btn_modificarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarLibroMouseEntered
        returnPreButtonStyle(btn_modificarLibro, "../icons/icons8_book_and_pencil_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_modificarLibroMouseEntered

    private void btn_modificarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarLibroMouseExited
        returnPreButtonStyle(btn_modificarLibro, "../icons/icons8_book_and_pencil_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_modificarLibroMouseExited

    private void btn_eliminarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMouseEntered
        returnPreButtonStyle(btn_eliminarLibro, "../icons/icons8_delete_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_eliminarLibroMouseEntered

    private void btn_eliminarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMouseExited
        returnPreButtonStyle(btn_eliminarLibro, "../icons/icons8_delete_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_eliminarLibroMouseExited

    private void btn_buscarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarLibroMouseEntered
        btn_buscarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_1.png")));
    }//GEN-LAST:event_btn_buscarLibroMouseEntered

    private void btn_buscarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarLibroMouseExited
        btn_buscarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_3.png")));
    }//GEN-LAST:event_btn_buscarLibroMouseExited

    public void setTableData(String texto){
        model.setRowCount(0);
        try {
            ResultSet rs = cxn.consultaLibros(texto+'%');
            while(rs.next()){
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                data[7] = rs.getString(8);
                data[8] = rs.getString(9);
                data[9] = rs.getString(10);
                data[10] = rs.getString(11);
                data[11] = rs.getString(12);
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.out);
        }
    }
    
    private void txtf_buscadorLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscadorLibroKeyTyped
        if((int)evt.getKeyChar() != 8)
            textoBuscador = txtf_buscadorLibro.getText() + evt.getKeyChar();
        else
            textoBuscador = txtf_buscadorLibro.getText();
        setTableData(textoBuscador);
        if(textoBuscador.length() > 150)
            evt.consume();
    }//GEN-LAST:event_txtf_buscadorLibroKeyTyped

    private void btn_registrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseClicked
        if(vRegistrar==null) {
            vRegistrar = new RegistrarLibro(cxn, this);
            vRegistrar.setVisible(true);
        } else{
            vRegistrar.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarLibroMouseClicked
 
    private String[] obtenerDatosFila(int fila){
        String[] libro = new String[12];
        libro[0] = (String) table_libros.getValueAt(fila, 0);
        libro[1] = (String) table_libros.getValueAt(fila, 1);
        libro[2] = (String) table_libros.getValueAt(fila, 2);
        libro[3] = (String) table_libros.getValueAt(fila, 3);
        libro[4] = (String) table_libros.getValueAt(fila, 4);
        libro[5] = (String) table_libros.getValueAt(fila, 5);
        libro[6] = (String) table_libros.getValueAt(fila, 6);
        libro[7] = (String) table_libros.getValueAt(fila, 7);
        libro[8] = (String) table_libros.getValueAt(fila, 8);
        libro[9] = (String) table_libros.getValueAt(fila, 9);
        libro[10] = (String) table_libros.getValueAt(fila, 10);
        libro[11] = (String) table_libros.getValueAt(fila, 11);
        return libro;
    }
    
    private void btn_modificarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarLibroMouseClicked
        int sRow = table_libros.getSelectedRow();
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un libro de la tabla", "Codex", 2);
        else{
            ModificarLibro vModificar = new ModificarLibro(obtenerDatosFila(sRow), cxn, this);
            vModificar.setVisible(true);
        }
            
    }//GEN-LAST:event_btn_modificarLibroMouseClicked

    private void btn_registrarLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMousePressed
       
    }//GEN-LAST:event_btn_registrarLibroMousePressed

    private void btn_registrarLibroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarLibroMouseReleased
        
    }//GEN-LAST:event_btn_registrarLibroMouseReleased

    private void btn_eliminarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMouseClicked
        int sRow = table_libros.getSelectedRow();
        String[] datos;
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un libro de la tabla", "Codex", 2);
        else{
            datos = obtenerDatosFila(sRow);
            Calendar date = Calendar.getInstance();
            String dia = Integer.toString(date.get(Calendar.DATE));
            String mes = Integer.toString(date.get(Calendar.MONTH)+1);
            String ano = Integer.toString(date.get(Calendar.YEAR));
            String fecha = ano+"-"+mes+"-"+dia;
            try {
                cxn.eliminarLibro(Integer.parseInt(datos[0]),fecha);
                this.setTableData("");
                JOptionPane.showMessageDialog(null, "Registro de libro eliminado.","Codex",1);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(),"Codex",0);
            }
        }
    }//GEN-LAST:event_btn_eliminarLibroMouseClicked

    private void txtf_buscadorLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscadorLibroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_buscadorLibroKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buscarLibro;
    private javax.swing.JLabel btn_eliminarLibro;
    private javax.swing.JLabel btn_modificarLibro;
    private javax.swing.JLabel btn_registrarLibro;
    private javax.swing.JComboBox<String> cmb_ordenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JPanel panel_buscadorLibro;
    private javax.swing.JPanel panel_opcionesBtnLibros;
    private javax.swing.JTable table_libros;
    private javax.swing.JTextField txtf_buscadorLibro;
    // End of variables declaration//GEN-END:variables
    private RegistrarLibro vRegistrar;
    StmtSQL cxn;
    String[] data = new String[12];
    private String textoBuscador;
    DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
}
