/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.StmtSQL;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author fresh-fresh
 */
public class Miembros extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     */
    public Miembros(StmtSQL cxn) {
        initComponents();
        setSize(630,460);
        this.cxn = cxn;
        new TextPrompt("   Buscar Miembro... ", txtf_buscadorUsuario);
        configTable();
        setTableData("");
    }

    private void configTable(){
        model.addColumn("ID");
        model.addColumn("CLAVE");
        model.addColumn("NOMBRE");
        model.addColumn("FECHA_NACIMIENTO");
        model.addColumn("DOMICILIO");
        model.addColumn("TELEFONO");
        model.addColumn("CORREO");
        model.addColumn("FECHA_INSCRIPCION");
        model.addColumn("FECHA_BAJA");
        table_miembros.setModel(model);
        TableColumnModel columnModel = table_miembros.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(35);
        columnModel.getColumn(1).setPreferredWidth(70);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(150);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(130);
        columnModel.getColumn(7).setPreferredWidth(130);
        columnModel.getColumn(8).setPreferredWidth(110);
    }
    
    public void setTableData(String texto){
        model.setRowCount(0);
        try {
            ResultSet rs = cxn.consultarMiembros(texto+"%");
            while(rs.next()){
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                data[7] = rs.getString(8);
                data[8] = rs.getString(9);
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.out);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_buscadorUsuario = new javax.swing.JPanel();
        txtf_buscadorUsuario = new javax.swing.JTextField();
        btn_buscarUsuario = new javax.swing.JLabel();
        cmb_ordenar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_miembros = new javax.swing.JTable();
        panel_opcionesBtnPrestamos = new javax.swing.JPanel();
        btn_registrarUsuario = new javax.swing.JLabel();
        btn_modificarUsuario = new javax.swing.JLabel();
        lbl_opciones = new javax.swing.JLabel();
        btn_eliminarUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(101, 121, 146));
        setPreferredSize(new java.awt.Dimension(630, 460));

        panel_buscadorUsuario.setBackground(new java.awt.Color(71, 91, 116));

        txtf_buscadorUsuario.setBackground(new java.awt.Color(161, 181, 206));
        txtf_buscadorUsuario.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtf_buscadorUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_buscadorUsuario.setToolTipText("Buscar por Nombre (usuario) o clave de usuario.");
        txtf_buscadorUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtf_buscadorUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_buscadorUsuarioKeyTyped(evt);
            }
        });

        btn_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px_3.png"))); // NOI18N
        btn_buscarUsuario.setToolTipText("Buscar");
        btn_buscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarUsuarioMouseExited(evt);
            }
        });

        cmb_ordenar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cmb_ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por", "Clave", "Nombre", "Fecha nacimiento", "Correo" }));

        javax.swing.GroupLayout panel_buscadorUsuarioLayout = new javax.swing.GroupLayout(panel_buscadorUsuario);
        panel_buscadorUsuario.setLayout(panel_buscadorUsuarioLayout);
        panel_buscadorUsuarioLayout.setHorizontalGroup(
            panel_buscadorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buscadorUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtf_buscadorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_buscadorUsuarioLayout.setVerticalGroup(
            panel_buscadorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_buscadorUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_buscadorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_buscadorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtf_buscadorUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscarUsuario, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        table_miembros.setBackground(new java.awt.Color(161, 181, 206));
        table_miembros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        table_miembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_miembros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table_miembros);
        if (table_miembros.getColumnModel().getColumnCount() > 0) {
            table_miembros.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_miembros.getColumnModel().getColumn(1).setPreferredWidth(70);
            table_miembros.getColumnModel().getColumn(2).setPreferredWidth(150);
            table_miembros.getColumnModel().getColumn(3).setPreferredWidth(150);
            table_miembros.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_miembros.getColumnModel().getColumn(5).setPreferredWidth(100);
            table_miembros.getColumnModel().getColumn(6).setPreferredWidth(100);
            table_miembros.getColumnModel().getColumn(7).setPreferredWidth(100);
            table_miembros.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        panel_opcionesBtnPrestamos.setBackground(new java.awt.Color(71, 91, 116));

        btn_registrarUsuario.setBackground(new java.awt.Color(230, 230, 230));
        btn_registrarUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_registrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_user_male_30px.png"))); // NOI18N
        btn_registrarUsuario.setText("Registrar");
        btn_registrarUsuario.setToolTipText("Registrar nuevo usuario.");
        btn_registrarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_registrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarUsuario.setOpaque(true);
        btn_registrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseReleased(evt);
            }
        });

        btn_modificarUsuario.setBackground(new java.awt.Color(230, 230, 230));
        btn_modificarUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_modificarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_change_user_30px.png"))); // NOI18N
        btn_modificarUsuario.setText("Modificar");
        btn_modificarUsuario.setToolTipText("Modificar usuario registrado.");
        btn_modificarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_modificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificarUsuario.setOpaque(true);
        btn_modificarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarUsuarioMouseExited(evt);
            }
        });

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setText("Opciones:");

        btn_eliminarUsuario.setBackground(new java.awt.Color(230, 230, 230));
        btn_eliminarUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_eliminarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_30px.png"))); // NOI18N
        btn_eliminarUsuario.setText("Eliminar");
        btn_eliminarUsuario.setToolTipText("Eliminar usuario.");
        btn_eliminarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_eliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminarUsuario.setOpaque(true);
        btn_eliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_opcionesBtnPrestamosLayout = new javax.swing.GroupLayout(panel_opcionesBtnPrestamos);
        panel_opcionesBtnPrestamos.setLayout(panel_opcionesBtnPrestamosLayout);
        panel_opcionesBtnPrestamosLayout.setHorizontalGroup(
            panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btn_registrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_opcionesBtnPrestamosLayout.setVerticalGroup(
            panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnPrestamosLayout.createSequentialGroup()
                .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_opcionesBtnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_buscadorUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_buscadorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel_opcionesBtnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
      
    private void returnPreButtonStyle(javax.swing.JLabel btn, String filename, String font, int styleFont, int textSize, Color col){
        btn.setIcon(new ImageIcon(this.getClass().getResource(filename)));
        btn.setFont(new Font(font, styleFont, textSize));
        btn.setBackground(col);
    }
    
    private void btn_registrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseEntered
        returnPreButtonStyle(btn_registrarUsuario, "../icons/icons8_add_user_male_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_registrarUsuarioMouseEntered

    private void btn_registrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseExited
        returnPreButtonStyle(btn_registrarUsuario, "../icons/icons8_add_user_male_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarUsuarioMouseExited

    private void btn_modificarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarUsuarioMouseEntered
        returnPreButtonStyle(btn_modificarUsuario, "../icons/icons8_change_user_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_modificarUsuarioMouseEntered

    private void btn_modificarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarUsuarioMouseExited
        returnPreButtonStyle(btn_modificarUsuario, "../icons/icons8_change_user_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_modificarUsuarioMouseExited

    private void btn_buscarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioMouseEntered
        btn_buscarUsuario.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_1.png")));
    }//GEN-LAST:event_btn_buscarUsuarioMouseEntered

    private void btn_buscarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioMouseExited
        btn_buscarUsuario.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_3.png")));
    }//GEN-LAST:event_btn_buscarUsuarioMouseExited

    private void txtf_buscadorUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscadorUsuarioKeyTyped
        if((int)evt.getKeyChar() != 8)
            textoBuscador = txtf_buscadorUsuario.getText() + evt.getKeyChar();
        else
            textoBuscador = txtf_buscadorUsuario.getText();
        setTableData(textoBuscador);
        if(txtf_buscadorUsuario.getText().length() >= 100)
            evt.consume();
    }//GEN-LAST:event_txtf_buscadorUsuarioKeyTyped

    private void btn_registrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseClicked
        if(vRegistrar==null) {
            vRegistrar = new RegistrarMiembro(cxn, this);
            vRegistrar.setVisible(true);
        } else{
            vRegistrar.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarUsuarioMouseClicked

    private String[] obtenerDatosFila(int fila){
        String[] miembro = new String[9];
        miembro[0] = (String) table_miembros.getValueAt(fila, 0);
        miembro[1] = (String) table_miembros.getValueAt(fila, 1);
        miembro[2] = (String) table_miembros.getValueAt(fila, 2);
        miembro[3] = (String) table_miembros.getValueAt(fila, 3);
        miembro[4] = (String) table_miembros.getValueAt(fila, 4);
        miembro[5] = (String) table_miembros.getValueAt(fila, 5);
        miembro[6] = (String) table_miembros.getValueAt(fila, 6);
        miembro[7] = (String) table_miembros.getValueAt(fila, 7);
        miembro[8] = (String) table_miembros.getValueAt(fila, 8);
        return miembro;
    }
    
    private void btn_modificarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarUsuarioMouseClicked
        int sRow = table_miembros.getSelectedRow();
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un miembro de la tabla", "Codex", 2);
        else{
            ModificarMiembro vModificar = new ModificarMiembro(obtenerDatosFila(sRow), cxn, this);
            vModificar.setVisible(true);
        }
    }//GEN-LAST:event_btn_modificarUsuarioMouseClicked

    private void btn_registrarUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMousePressed
       
    }//GEN-LAST:event_btn_registrarUsuarioMousePressed

    private void btn_registrarUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseReleased
        
    }//GEN-LAST:event_btn_registrarUsuarioMouseReleased

    private void btn_eliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseClicked
        int sRow = table_miembros.getSelectedRow();
        String[] datos;
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un miembro de la tabla", "Codex", 2);
        else{
            datos = obtenerDatosFila(sRow);
            Calendar date = Calendar.getInstance();
            String dia = Integer.toString(date.get(Calendar.DATE));
            String mes = Integer.toString(date.get(Calendar.MONTH)+1);
            String ano = Integer.toString(date.get(Calendar.YEAR));
            String fecha = ano+"-"+mes+"-"+dia;
            try {
                cxn.eliminarMiembro(Integer.parseInt(datos[0]),fecha);
                this.setTableData("");
                JOptionPane.showMessageDialog(null, "Registro de miembro eliminado.","Codex",1);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(),"Codex",0);
            }
        }
    }//GEN-LAST:event_btn_eliminarUsuarioMouseClicked

    private void btn_eliminarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseEntered
        returnPreButtonStyle(btn_eliminarUsuario, "../icons/icons8_delete_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_eliminarUsuarioMouseEntered

    private void btn_eliminarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseExited
        returnPreButtonStyle(btn_eliminarUsuario, "../icons/icons8_delete_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_eliminarUsuarioMouseExited

    private void btn_eliminarUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarUsuarioMousePressed

    private void btn_eliminarUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarUsuarioMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buscarUsuario;
    private javax.swing.JLabel btn_eliminarUsuario;
    private javax.swing.JLabel btn_modificarUsuario;
    private javax.swing.JLabel btn_registrarUsuario;
    private javax.swing.JComboBox<String> cmb_ordenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JPanel panel_buscadorUsuario;
    private javax.swing.JPanel panel_opcionesBtnPrestamos;
    private javax.swing.JTable table_miembros;
    private javax.swing.JTextField txtf_buscadorUsuario;
    // End of variables declaration//GEN-END:variables
    private RegistrarMiembro vRegistrar;
    StmtSQL cxn;
    String[] data =  new String[9];
    String textoBuscador;
    DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
}
