/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.StmtSQL;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fresh-fresh
 */
public class ModificarMiembro extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarLibro
     */
    public ModificarMiembro(String[] sMiembro, StmtSQL cxn, Miembros vMiembros) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.cxn = cxn;
        this.vMiembros = vMiembros;
        this.sMiembro = sMiembro;
        this.setTitle("Modificar Usuario");
        new TextPrompt("  Nombre", txtf_nombre);
        new TextPrompt("  domicilio", txtf_domicilio); 
        new TextPrompt("  Número teléfono", txtf_numTelefono);
        new TextPrompt("  Correo electronico", txtf_email);
        try{
            setDataModMiembro();
        } catch(ParseException e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        main_panelRegistroLibro = new javax.swing.JPanel();
        panel_windowOpRegistroLibro = new javax.swing.JPanel();
        btn_exitRegistrarLibro = new javax.swing.JLabel();
        btn_minimizeRegistrarLibro = new javax.swing.JLabel();
        lbl_titleModUsuario = new javax.swing.JLabel();
        panel_formulario = new javax.swing.JPanel();
        line_nombreUsuario = new javax.swing.JSeparator();
        txtf_nombre = new javax.swing.JTextField();
        line_email = new javax.swing.JSeparator();
        txtf_domicilio = new javax.swing.JTextField();
        dc_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        line_numTelefono = new javax.swing.JSeparator();
        txtf_numTelefono = new javax.swing.JTextField();
        lbl_fechaNacimiento = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtf_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(420, 271));

        main_panelRegistroLibro.setBackground(new java.awt.Color(71, 91, 116));
        main_panelRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 350));
        main_panelRegistroLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_windowOpRegistroLibro.setBackground(new java.awt.Color(31, 51, 76));
        panel_windowOpRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 30));
        panel_windowOpRegistroLibro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMouseDragged(evt);
            }
        });
        panel_windowOpRegistroLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMousePressed(evt);
            }
        });

        btn_exitRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitRegistrarLibro.setToolTipText("Cerrar");
        btn_exitRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseExited(evt);
            }
        });

        btn_minimizeRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeRegistrarLibro.setToolTipText("Minimizar");
        btn_minimizeRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_windowOpRegistroLibroLayout = new javax.swing.GroupLayout(panel_windowOpRegistroLibro);
        panel_windowOpRegistroLibro.setLayout(panel_windowOpRegistroLibroLayout);
        panel_windowOpRegistroLibroLayout.setHorizontalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_windowOpRegistroLibroLayout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(btn_minimizeRegistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exitRegistrarLibro)
                .addGap(86, 86, 86))
        );
        panel_windowOpRegistroLibroLayout.setVerticalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_minimizeRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(btn_exitRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panelRegistroLibro.add(panel_windowOpRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        lbl_titleModUsuario.setBackground(new java.awt.Color(51, 71, 96));
        lbl_titleModUsuario.setFont(new java.awt.Font("Kristen ITC", 0, 16)); // NOI18N
        lbl_titleModUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titleModUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_edit_account_25px.png"))); // NOI18N
        lbl_titleModUsuario.setText("Modificar Usuario");
        lbl_titleModUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 121, 146), 2, true));
        lbl_titleModUsuario.setOpaque(true);
        main_panelRegistroLibro.add(lbl_titleModUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 30));

        panel_formulario.setBackground(new java.awt.Color(51, 71, 96));
        panel_formulario.setPreferredSize(new java.awt.Dimension(350, 350));

        line_nombreUsuario.setBackground(new java.awt.Color(131, 151, 176));
        line_nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));

        txtf_nombre.setBackground(new java.awt.Color(51, 71, 96));
        txtf_nombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txtf_nombre.setBorder(null);
        txtf_nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_nombre.setOpaque(false);
        txtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_nombreKeyTyped(evt);
            }
        });

        line_email.setBackground(new java.awt.Color(131, 151, 176));
        line_email.setForeground(new java.awt.Color(0, 0, 0));

        txtf_domicilio.setBackground(new java.awt.Color(51, 71, 96));
        txtf_domicilio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_domicilio.setForeground(new java.awt.Color(255, 255, 255));
        txtf_domicilio.setBorder(null);
        txtf_domicilio.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_domicilio.setOpaque(false);
        txtf_domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_domicilioKeyTyped(evt);
            }
        });

        dc_fechaNacimiento.setBackground(new java.awt.Color(151, 171, 196));
        dc_fechaNacimiento.setDateFormatString("yyyy-MM-dd");

        line_numTelefono.setBackground(new java.awt.Color(131, 151, 176));
        line_numTelefono.setForeground(new java.awt.Color(0, 0, 0));

        txtf_numTelefono.setBackground(new java.awt.Color(51, 71, 96));
        txtf_numTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_numTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtf_numTelefono.setBorder(null);
        txtf_numTelefono.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_numTelefono.setOpaque(false);
        txtf_numTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_numTelefonoKeyTyped(evt);
            }
        });

        lbl_fechaNacimiento.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        lbl_fechaNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        lbl_fechaNacimiento.setText("Fecha Nacimiento");

        btn_guardar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_17px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_17px.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txtf_email.setBackground(new java.awt.Color(51, 71, 96));
        txtf_email.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_email.setForeground(new java.awt.Color(255, 255, 255));
        txtf_email.setBorder(null);
        txtf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_emailKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_formularioLayout = new javax.swing.GroupLayout(panel_formulario);
        panel_formulario.setLayout(panel_formularioLayout);
        panel_formularioLayout.setHorizontalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_formularioLayout.createSequentialGroup()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_email)
                            .addComponent(jSeparator1))
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_formularioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(line_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtf_domicilio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line_numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(234, 234, 234))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fechaNacimiento)
                            .addComponent(dc_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_formularioLayout.setVerticalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addComponent(txtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addComponent(lbl_fechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addComponent(txtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(line_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dc_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line_email, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line_numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guardar)
                            .addComponent(btn_cancelar))))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        main_panelRegistroLibro.add(panel_formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDataModMiembro() throws ParseException{
        txtf_nombre.setText(sMiembro[2]);
        java.util.Date fechaParseada= new java.text.SimpleDateFormat("yyyy-MM-dd").parse(sMiembro[3]);
        dc_fechaNacimiento.setDate(fechaParseada);
        txtf_domicilio.setText(sMiembro[4]);
        txtf_numTelefono.setText(sMiembro[5]);
        txtf_email.setText(sMiembro[6]);
    }
    
    private void btn_exitRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseClicked
        vMiembros.setTableData("");
        this.dispose();
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseClicked

    private void btn_exitRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseEntered
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseEntered

    private void btn_exitRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseExited
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseExited

    private void btn_minimizeRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseClicked

    private void btn_minimizeRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseEntered
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseEntered

    private void btn_minimizeRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseExited
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseExited

    private void panel_windowOpRegistroLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_windowOpRegistroLibroMousePressed

    private void panel_windowOpRegistroLibroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_panel_windowOpRegistroLibroMouseDragged

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        vMiembros.setTableData("");
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_nombreKeyTyped
        if(txtf_nombre.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtf_nombreKeyTyped

    private void txtf_domicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_domicilioKeyTyped
        if(txtf_domicilio.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtf_domicilioKeyTyped

    private void txtf_numTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_numTelefonoKeyTyped
        if(txtf_numTelefono.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txtf_numTelefonoKeyTyped

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarMouseClicked

    public void obtenerDatosMiembro(){
        sMiembro[2] = txtf_nombre.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        Calendar f = dc_fechaNacimiento.getCalendar();
        sMiembro[3] = f.get(Calendar.YEAR)+"-"+(f.get(Calendar.MONTH)+1)+"-"+f.get(Calendar.DATE);
        sMiembro[4] = txtf_domicilio.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sMiembro[5] = txtf_numTelefono.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sMiembro[6] = txtf_email.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        obtenerDatosMiembro();
        try {
            cxn.modificarMiembro(sMiembro);
            JOptionPane.showMessageDialog(null, "Se ha modificado el registro.", "Codex",1);
            btn_cancelarActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(), "Codex",1);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtf_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_emailKeyTyped
        if(txtf_email.getText().length() >= 70)
            evt.consume();
    }//GEN-LAST:event_txtf_emailKeyTyped
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel btn_exitRegistrarLibro;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel btn_minimizeRegistrarLibro;
    private com.toedter.calendar.JDateChooser dc_fechaNacimiento;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_fechaNacimiento;
    private javax.swing.JLabel lbl_titleModUsuario;
    private javax.swing.JSeparator line_email;
    private javax.swing.JSeparator line_nombreUsuario;
    private javax.swing.JSeparator line_numTelefono;
    private javax.swing.JPanel main_panelRegistroLibro;
    private javax.swing.JPanel panel_formulario;
    private javax.swing.JPanel panel_windowOpRegistroLibro;
    private javax.swing.JTextField txtf_domicilio;
    private javax.swing.JTextField txtf_email;
    private javax.swing.JTextField txtf_nombre;
    private javax.swing.JTextField txtf_numTelefono;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    StmtSQL cxn;
    Miembros vMiembros;
    String[] sMiembro = new String[9];
}
