/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import BD.StmtSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author fresh-fresh
 */
public class ModificarLibro extends javax.swing.JFrame {

    /**
     * Creates new form ModificarLibro
     */
    public ModificarLibro(String[] libro, StmtSQL cxn, Libros lib) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.setTitle("Modificar Libro");
        new TextPrompt("  Título", txtf_tituloLibro);
        new TextPrompt("  Nombre Autor", txtf_nombreAutor); 
        new TextPrompt("  ISBN", txtf_isbn); 
        new TextPrompt("  Editorial", txtf_editorial);
        new TextPrompt("  Lugar de publicación", txtf_lugarPub);
        new TextPrompt("  No. Páginas", txtf_numPaginas);
        new TextPrompt("  No. Libros", txtf_numLibros);
        new TextPrompt("  Año Publicación", txtf_fechaPub);
        this.cxn = cxn;
        this.lib = lib;
        sLibro = libro;
        txtf_tituloLibro.setText(libro[1]);
        txtf_nombreAutor.setText(libro[2]);
        txtf_isbn.setText(libro[7]);
        txtf_editorial.setText(libro[3]);
        txtf_numPaginas.setText(libro[4]);
        txtf_lugarPub.setText(libro[5]);
        txtf_numLibros.setText(libro[8]);
        txtf_fechaPub.setText(libro[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panelRegistroLibro = new javax.swing.JPanel();
        panel_windowOpRegistroLibro = new javax.swing.JPanel();
        btn_exitRegistrarLibro = new javax.swing.JLabel();
        btn_minimizeRegistrarLibro = new javax.swing.JLabel();
        lbl_titleRegistroLibro = new javax.swing.JLabel();
        panel_formulario = new javax.swing.JPanel();
        line_tituloLibro = new javax.swing.JSeparator();
        txtf_tituloLibro = new javax.swing.JTextField();
        line_nombreAutor = new javax.swing.JSeparator();
        line_numPaginas = new javax.swing.JSeparator();
        txtf_numPaginas = new javax.swing.JTextField();
        line_lugarPub = new javax.swing.JSeparator();
        txtf_lugarPub = new javax.swing.JTextField();
        txtf_nombreAutor = new javax.swing.JTextField();
        line_editorial = new javax.swing.JSeparator();
        txtf_editorial = new javax.swing.JTextField();
        line_isbn = new javax.swing.JSeparator();
        txtf_isbn = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        line_numLibros = new javax.swing.JSeparator();
        txtf_numLibros = new javax.swing.JTextField();
        btn_infoNumLibros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtf_fechaPub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panelRegistroLibro.setBackground(new java.awt.Color(71, 91, 116));
        main_panelRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 350));
        main_panelRegistroLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_windowOpRegistroLibro.setBackground(new java.awt.Color(31, 51, 76));
        panel_windowOpRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 30));
        panel_windowOpRegistroLibro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMouseDragged(evt);
            }
        });
        panel_windowOpRegistroLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMousePressed(evt);
            }
        });

        btn_exitRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitRegistrarLibro.setToolTipText("Cerrar");
        btn_exitRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseExited(evt);
            }
        });

        btn_minimizeRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeRegistrarLibro.setToolTipText("Minimizar");
        btn_minimizeRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_windowOpRegistroLibroLayout = new javax.swing.GroupLayout(panel_windowOpRegistroLibro);
        panel_windowOpRegistroLibro.setLayout(panel_windowOpRegistroLibroLayout);
        panel_windowOpRegistroLibroLayout.setHorizontalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_windowOpRegistroLibroLayout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(btn_minimizeRegistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exitRegistrarLibro)
                .addContainerGap())
        );
        panel_windowOpRegistroLibroLayout.setVerticalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_minimizeRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(btn_exitRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_exitRegistrarLibro.getAccessibleContext().setAccessibleName("Cerrar Ventana");
        btn_minimizeRegistrarLibro.getAccessibleContext().setAccessibleName("Minimizar Ventana");

        main_panelRegistroLibro.add(panel_windowOpRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        lbl_titleRegistroLibro.setBackground(new java.awt.Color(51, 71, 96));
        lbl_titleRegistroLibro.setFont(new java.awt.Font("Kristen ITC", 0, 16)); // NOI18N
        lbl_titleRegistroLibro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titleRegistroLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_and_pencil_25px.png"))); // NOI18N
        lbl_titleRegistroLibro.setText("Modificar Libro");
        lbl_titleRegistroLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 121, 146), 2, true));
        lbl_titleRegistroLibro.setOpaque(true);
        main_panelRegistroLibro.add(lbl_titleRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 30));

        panel_formulario.setBackground(new java.awt.Color(51, 71, 96));
        panel_formulario.setPreferredSize(new java.awt.Dimension(350, 350));

        line_tituloLibro.setBackground(new java.awt.Color(131, 151, 176));
        line_tituloLibro.setForeground(new java.awt.Color(0, 0, 0));

        txtf_tituloLibro.setBackground(new java.awt.Color(51, 71, 96));
        txtf_tituloLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_tituloLibro.setForeground(new java.awt.Color(255, 255, 255));
        txtf_tituloLibro.setBorder(null);
        txtf_tituloLibro.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_tituloLibro.setOpaque(false);
        txtf_tituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_tituloLibroKeyTyped(evt);
            }
        });

        line_nombreAutor.setBackground(new java.awt.Color(131, 151, 176));
        line_nombreAutor.setForeground(new java.awt.Color(0, 0, 0));

        line_numPaginas.setBackground(new java.awt.Color(131, 151, 176));
        line_numPaginas.setForeground(new java.awt.Color(0, 0, 0));

        txtf_numPaginas.setBackground(new java.awt.Color(51, 71, 96));
        txtf_numPaginas.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_numPaginas.setForeground(new java.awt.Color(255, 255, 255));
        txtf_numPaginas.setBorder(null);
        txtf_numPaginas.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_numPaginas.setOpaque(false);
        txtf_numPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_numPaginasKeyTyped(evt);
            }
        });

        line_lugarPub.setBackground(new java.awt.Color(131, 151, 176));
        line_lugarPub.setForeground(new java.awt.Color(0, 0, 0));

        txtf_lugarPub.setBackground(new java.awt.Color(51, 71, 96));
        txtf_lugarPub.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_lugarPub.setForeground(new java.awt.Color(255, 255, 255));
        txtf_lugarPub.setBorder(null);
        txtf_lugarPub.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_lugarPub.setOpaque(false);
        txtf_lugarPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_lugarPubActionPerformed(evt);
            }
        });
        txtf_lugarPub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_lugarPubKeyTyped(evt);
            }
        });

        txtf_nombreAutor.setBackground(new java.awt.Color(51, 71, 96));
        txtf_nombreAutor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_nombreAutor.setForeground(new java.awt.Color(255, 255, 255));
        txtf_nombreAutor.setBorder(null);
        txtf_nombreAutor.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_nombreAutor.setOpaque(false);
        txtf_nombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_nombreAutorKeyTyped(evt);
            }
        });

        line_editorial.setBackground(new java.awt.Color(131, 151, 176));
        line_editorial.setForeground(new java.awt.Color(0, 0, 0));

        txtf_editorial.setBackground(new java.awt.Color(51, 71, 96));
        txtf_editorial.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtf_editorial.setBorder(null);
        txtf_editorial.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_editorial.setOpaque(false);
        txtf_editorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_editorialKeyTyped(evt);
            }
        });

        line_isbn.setBackground(new java.awt.Color(131, 151, 176));
        line_isbn.setForeground(new java.awt.Color(0, 0, 0));

        txtf_isbn.setBackground(new java.awt.Color(51, 71, 96));
        txtf_isbn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_isbn.setForeground(new java.awt.Color(255, 255, 255));
        txtf_isbn.setBorder(null);
        txtf_isbn.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_isbn.setOpaque(false);
        txtf_isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_isbnKeyTyped(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_17px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_17px.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txtf_numLibros.setBackground(new java.awt.Color(51, 71, 96));
        txtf_numLibros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_numLibros.setForeground(new java.awt.Color(255, 255, 255));
        txtf_numLibros.setBorder(null);
        txtf_numLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_numLibrosKeyTyped(evt);
            }
        });

        btn_infoNumLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_help_14px_1.png"))); // NOI18N
        btn_infoNumLibros.setToolTipText("Cantidad de libros que desea registrar con los mismos datos.");
        btn_infoNumLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_infoNumLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_infoNumLibrosMouseEntered(evt);
            }
        });

        txtf_fechaPub.setBackground(new java.awt.Color(51, 71, 96));
        txtf_fechaPub.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_fechaPub.setForeground(new java.awt.Color(255, 255, 255));
        txtf_fechaPub.setBorder(null);
        txtf_fechaPub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_fechaPubKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_formularioLayout = new javax.swing.GroupLayout(panel_formulario);
        panel_formulario.setLayout(panel_formularioLayout);
        panel_formularioLayout.setHorizontalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_formularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(line_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(line_editorial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_editorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(line_nombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_nombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_lugarPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line_lugarPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(line_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtf_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(txtf_fechaPub, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addGap(117, 117, 117))
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(line_numLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtf_numLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_infoNumLibros)
                .addGap(81, 81, 81)
                .addComponent(btn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_formularioLayout.setVerticalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtf_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line_nombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(line_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtf_fechaPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_cancelar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtf_lugarPub, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line_lugarPub, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_numLibros)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_infoNumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line_numLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        main_panelRegistroLibro.add(panel_formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseClicked
        lib.setTableData("");
        this.dispose();
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseClicked

    private void btn_exitRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseEntered
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseEntered

    private void btn_exitRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseExited
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseExited

    private void btn_minimizeRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseClicked

    private void btn_minimizeRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseEntered
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseEntered

    private void btn_minimizeRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseExited
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseExited

    private void panel_windowOpRegistroLibroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_panel_windowOpRegistroLibroMouseDragged

    private void panel_windowOpRegistroLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_windowOpRegistroLibroMousePressed

    private void txtf_tituloLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_tituloLibroKeyTyped
        if(txtf_tituloLibro.getText().length() >= 100)
        evt.consume();
    }//GEN-LAST:event_txtf_tituloLibroKeyTyped

    private void txtf_numPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_numPaginasKeyTyped
        if(txtf_numPaginas.getText().length() >= 6)
        evt.consume();
    }//GEN-LAST:event_txtf_numPaginasKeyTyped

    private void txtf_lugarPubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_lugarPubKeyTyped
        if(txtf_lugarPub.getText().length() >= 50)
        evt.consume();
    }//GEN-LAST:event_txtf_lugarPubKeyTyped

    private void txtf_nombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_nombreAutorKeyTyped
        if(txtf_nombreAutor.getText().length() >= 50)
        evt.consume();
    }//GEN-LAST:event_txtf_nombreAutorKeyTyped

    private void txtf_editorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_editorialKeyTyped
        if(txtf_editorial.getText().length() >= 50)
        evt.consume();
    }//GEN-LAST:event_txtf_editorialKeyTyped

    private void txtf_isbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_isbnKeyTyped
        if(txtf_isbn.getText().length() >= 13)
        evt.consume();
    }//GEN-LAST:event_txtf_isbnKeyTyped

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        lib.setTableData("");
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txtf_numLibrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_numLibrosKeyTyped
        if(txtf_numLibros.getText().length() >= 6)
            evt.consume();
    }//GEN-LAST:event_txtf_numLibrosKeyTyped

    private void btn_infoNumLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_infoNumLibrosMouseEntered
        
    }//GEN-LAST:event_btn_infoNumLibrosMouseEntered

    private void txtf_lugarPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_lugarPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_lugarPubActionPerformed

    private void txtf_fechaPubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_fechaPubKeyTyped
        if(txtf_fechaPub.getText().length() >= 4)
            evt.consume();
    }//GEN-LAST:event_txtf_fechaPubKeyTyped

    public void obtenerDatosLibro(){
        sLibro[1] = txtf_tituloLibro.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[2] = txtf_nombreAutor.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[7] = txtf_isbn.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[3] = txtf_editorial.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[4] = txtf_numPaginas.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[5] = txtf_lugarPub.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[8] = txtf_numLibros.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        sLibro[6] = txtf_fechaPub.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
    }

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        obtenerDatosLibro();
        sLibro[9] = sLibro[8];
        try {
            int cLibros = cxn.contarLibrosPrestados(sLibro[0]);
            sLibro[9] = Integer.toString(Integer.parseInt(sLibro[9]) - cLibros);
            cxn.modificarLibro(sLibro);
            JOptionPane.showMessageDialog(null, "Se ha modificado el registro.", "Codex",1);
            btn_cancelarActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(), "Codex",1);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel btn_exitRegistrarLibro;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel btn_infoNumLibros;
    private javax.swing.JLabel btn_minimizeRegistrarLibro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_titleRegistroLibro;
    private javax.swing.JSeparator line_editorial;
    private javax.swing.JSeparator line_isbn;
    private javax.swing.JSeparator line_lugarPub;
    private javax.swing.JSeparator line_nombreAutor;
    private javax.swing.JSeparator line_numLibros;
    private javax.swing.JSeparator line_numPaginas;
    private javax.swing.JSeparator line_tituloLibro;
    private javax.swing.JPanel main_panelRegistroLibro;
    private javax.swing.JPanel panel_formulario;
    private javax.swing.JPanel panel_windowOpRegistroLibro;
    private javax.swing.JTextField txtf_editorial;
    private javax.swing.JTextField txtf_fechaPub;
    private javax.swing.JTextField txtf_isbn;
    private javax.swing.JTextField txtf_lugarPub;
    private javax.swing.JTextField txtf_nombreAutor;
    private javax.swing.JTextField txtf_numLibros;
    private javax.swing.JTextField txtf_numPaginas;
    private javax.swing.JTextField txtf_tituloLibro;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    String[] sLibro;
    StmtSQL cxn;
    Libros lib;
}
