/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.StmtSQL;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author fresh-fresh
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     * @param cxn
     */
    public Prestamos(StmtSQL cxn) {
        initComponents();
        setSize(630,460);
        this.cxn = cxn;
        new TextPrompt("   Buscar Préstamo... ", txtf_buscadorPrestamo);
        configTable();
        setTableData("");
    }

    private void configTable(){
        model.addColumn("ID");
        model.addColumn("ID_MIEMBRO");
        model.addColumn("ID_LIBRO");
        model.addColumn("NOMBRE_MIEMBRO");
        model.addColumn("TITULO_LIBRO");
        model.addColumn("FECHA_PRESTAMO");
        model.addColumn("FECHA_ENTREGA");
        table_prestamos.setModel(model);
        TableColumnModel columnModel = table_prestamos.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(35);
        columnModel.getColumn(1).setPreferredWidth(80);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(150);
        columnModel.getColumn(5).setPreferredWidth(130);
        columnModel.getColumn(6).setPreferredWidth(130);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_buscadorPrestamo = new javax.swing.JPanel();
        txtf_buscadorPrestamo = new javax.swing.JTextField();
        btn_buscarPrestamo = new javax.swing.JLabel();
        cmb_ordenar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestamos = new javax.swing.JTable();
        panel_opcionesBtnPrestamos = new javax.swing.JPanel();
        btn_registrarPrestamo = new javax.swing.JLabel();
        btn_modificarPrestamo = new javax.swing.JLabel();
        lbl_opciones = new javax.swing.JLabel();
        btn_eliminarPrestamo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(101, 121, 146));
        setPreferredSize(new java.awt.Dimension(630, 460));

        panel_buscadorPrestamo.setBackground(new java.awt.Color(71, 91, 116));

        txtf_buscadorPrestamo.setBackground(new java.awt.Color(161, 181, 206));
        txtf_buscadorPrestamo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtf_buscadorPrestamo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_buscadorPrestamo.setToolTipText("Buscar por nombre prestatario (miembro).");
        txtf_buscadorPrestamo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtf_buscadorPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_buscadorPrestamoKeyTyped(evt);
            }
        });

        btn_buscarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px_3.png"))); // NOI18N
        btn_buscarPrestamo.setToolTipText("Buscar");
        btn_buscarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarPrestamoMouseExited(evt);
            }
        });

        cmb_ordenar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cmb_ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por", "Titulo libro", "Nombre prestatario", "Fecha de préstamo", "Feche entrega" }));

        javax.swing.GroupLayout panel_buscadorPrestamoLayout = new javax.swing.GroupLayout(panel_buscadorPrestamo);
        panel_buscadorPrestamo.setLayout(panel_buscadorPrestamoLayout);
        panel_buscadorPrestamoLayout.setHorizontalGroup(
            panel_buscadorPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buscadorPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtf_buscadorPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_buscadorPrestamoLayout.setVerticalGroup(
            panel_buscadorPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_buscadorPrestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_buscadorPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_buscadorPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtf_buscadorPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscarPrestamo, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        table_prestamos.setBackground(new java.awt.Color(161, 181, 206));
        table_prestamos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        table_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prestamos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table_prestamos);

        panel_opcionesBtnPrestamos.setBackground(new java.awt.Color(71, 91, 116));

        btn_registrarPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btn_registrarPrestamo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_registrarPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cash_in_hand_30px.png"))); // NOI18N
        btn_registrarPrestamo.setText("Registrar");
        btn_registrarPrestamo.setToolTipText("Registrar nuevo préstamo.");
        btn_registrarPrestamo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_registrarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarPrestamo.setOpaque(true);
        btn_registrarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_registrarPrestamoMouseReleased(evt);
            }
        });

        btn_modificarPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btn_modificarPrestamo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_modificarPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_edit_property_30px_2.png"))); // NOI18N
        btn_modificarPrestamo.setText("Modificar");
        btn_modificarPrestamo.setToolTipText("Modificar préstamo registrado.");
        btn_modificarPrestamo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_modificarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificarPrestamo.setOpaque(true);
        btn_modificarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarPrestamoMouseExited(evt);
            }
        });

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setText("Opciones:");

        btn_eliminarPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btn_eliminarPrestamo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_eliminarPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_30px.png"))); // NOI18N
        btn_eliminarPrestamo.setText("Eliminar");
        btn_eliminarPrestamo.setToolTipText("Eliminar préstamo (Automáticamente se hará registro de una devolución).");
        btn_eliminarPrestamo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 181, 206), 1, true));
        btn_eliminarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminarPrestamo.setOpaque(true);
        btn_eliminarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_eliminarPrestamoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_opcionesBtnPrestamosLayout = new javax.swing.GroupLayout(panel_opcionesBtnPrestamos);
        panel_opcionesBtnPrestamos.setLayout(panel_opcionesBtnPrestamosLayout);
        panel_opcionesBtnPrestamosLayout.setHorizontalGroup(
            panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btn_registrarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_opcionesBtnPrestamosLayout.setVerticalGroup(
            panel_opcionesBtnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesBtnPrestamosLayout.createSequentialGroup()
                .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_opcionesBtnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_buscadorPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_buscadorPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(panel_opcionesBtnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnPreButtonStyle(javax.swing.JLabel btn, String filename, String font, int styleFont, int textSize, Color col){
        btn.setIcon(new ImageIcon(this.getClass().getResource(filename)));
        btn.setFont(new Font(font, styleFont, textSize));
        btn.setBackground(col);
    }
    
    private void btn_registrarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseEntered
        returnPreButtonStyle(btn_registrarPrestamo, "../icons/icons8_cash_in_hand_30px_1.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_registrarPrestamoMouseEntered

    private void btn_registrarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseExited
        returnPreButtonStyle(btn_registrarPrestamo, "../icons/icons8_cash_in_hand_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_registrarPrestamoMouseExited

    private void btn_modificarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarPrestamoMouseEntered
        returnPreButtonStyle(btn_modificarPrestamo, "../icons/icons8_edit_property_30px_3.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_modificarPrestamoMouseEntered

    private void btn_modificarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarPrestamoMouseExited
        returnPreButtonStyle(btn_modificarPrestamo, "../icons/icons8_edit_property_30px_2.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_modificarPrestamoMouseExited

    private void btn_buscarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarPrestamoMouseEntered
        btn_buscarPrestamo.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_1.png")));
    }//GEN-LAST:event_btn_buscarPrestamoMouseEntered

    private void btn_buscarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarPrestamoMouseExited
        btn_buscarPrestamo.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_3.png")));
    }//GEN-LAST:event_btn_buscarPrestamoMouseExited

    public void setTableData(String texto){
        model.setRowCount(0);
        try {
            ResultSet rs = cxn.consultarPrestamos(texto+"%");
            while(rs.next()){
                data[0] = rs.getString(1);
                data[2] = rs.getString(2);
                data[1] = rs.getString(3);
                data[4] = rs.getString(4);
                data[3] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.out);
        }
    }
    
    private void txtf_buscadorPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscadorPrestamoKeyTyped
        if((int)evt.getKeyChar() != 8)
            textoBuscador = txtf_buscadorPrestamo.getText() + evt.getKeyChar();
        else
            textoBuscador = txtf_buscadorPrestamo.getText();
        setTableData(textoBuscador);
        if(txtf_buscadorPrestamo.getText().length() >= 150)
            evt.consume();
    }//GEN-LAST:event_txtf_buscadorPrestamoKeyTyped

    private void btn_registrarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseClicked
        if(vRegistrar==null) {
            vRegistrar = new RegistrarPrestamo(cxn);
            vRegistrar.setVisible(true);
        } else{
            vRegistrar.setVisible(true);
        }
    }//GEN-LAST:event_btn_registrarPrestamoMouseClicked

    private String[] obtenerDatosFila(int fila){
        String[] prestamo = new String[7];
        prestamo[0] = (String) table_prestamos.getValueAt(fila, 0);
        prestamo[2] = (String) table_prestamos.getValueAt(fila, 1);
        prestamo[1] = (String) table_prestamos.getValueAt(fila, 2);
        prestamo[4] = (String) table_prestamos.getValueAt(fila, 3);
        prestamo[3] = (String) table_prestamos.getValueAt(fila, 4);
        prestamo[5] = (String) table_prestamos.getValueAt(fila, 5);
        prestamo[6] = (String) table_prestamos.getValueAt(fila, 6);
        return prestamo;
    }
    
    private void btn_modificarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarPrestamoMouseClicked
        int sRow = table_prestamos.getSelectedRow();
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un Prestamo de la tabla", "Codex", 2);
        else{
            ModificarPrestamo vModificar = new ModificarPrestamo(obtenerDatosFila(sRow), cxn, this);
            vModificar.setVisible(true);
        }
    }//GEN-LAST:event_btn_modificarPrestamoMouseClicked

    private void btn_registrarPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMousePressed
       
    }//GEN-LAST:event_btn_registrarPrestamoMousePressed

    private void btn_registrarPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarPrestamoMouseReleased
        
    }//GEN-LAST:event_btn_registrarPrestamoMouseReleased

    private void btn_eliminarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPrestamoMouseClicked
        // Eliminar Prestamo y registra una devolucion
        int sRow = table_prestamos.getSelectedRow();
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un Prestamo de la tabla", "Codex", 2);
        else{
            String idprestamo = (String) table_prestamos.getValueAt(sRow, 0);
            try {
                float multa = cxn.consultarMulta(idprestamo);
                if(multa<0)
                    cxn.eliminarPrestamo(idprestamo);
                else{
                    int confirm = JOptionPane.showConfirmDialog(null,"Usuario tendra que pagar una multa de $" + multa + " MXN \nConfirmar para eliminar el registro del prestamo.", "Codex", 0,1);
                    if(confirm==0)
                        cxn.eliminarPrestamo(idprestamo);
                }
            } catch (SQLException ex) {
            }
            setTableData("");
        }
    }//GEN-LAST:event_btn_eliminarPrestamoMouseClicked

    private void btn_eliminarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPrestamoMouseEntered
        returnPreButtonStyle(btn_eliminarPrestamo, "../icons/icons8_delete_35px.png","Segoe UI Semilight", 0, 13, new Color(250,250,250));
    }//GEN-LAST:event_btn_eliminarPrestamoMouseEntered

    private void btn_eliminarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPrestamoMouseExited
        returnPreButtonStyle(btn_eliminarPrestamo, "../icons/icons8_delete_30px.png","Segoe UI Semilight", 0, 12, new Color(230,230,230));
    }//GEN-LAST:event_btn_eliminarPrestamoMouseExited

    private void btn_eliminarPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPrestamoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarPrestamoMousePressed

    private void btn_eliminarPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPrestamoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarPrestamoMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buscarPrestamo;
    private javax.swing.JLabel btn_eliminarPrestamo;
    private javax.swing.JLabel btn_modificarPrestamo;
    private javax.swing.JLabel btn_registrarPrestamo;
    private javax.swing.JComboBox<String> cmb_ordenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JPanel panel_buscadorPrestamo;
    private javax.swing.JPanel panel_opcionesBtnPrestamos;
    private javax.swing.JTable table_prestamos;
    private javax.swing.JTextField txtf_buscadorPrestamo;
    // End of variables declaration//GEN-END:variables
    private RegistrarPrestamo vRegistrar;
    StmtSQL cxn;
    String textoBuscador;
    String[] data = new String[7];
    DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
}
