/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.StmtSQL;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fresh-fresh
 */
public class RegistrarLibro extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarLibro
     */
    public RegistrarLibro(StmtSQL cxn, Libros lib) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.cxn = cxn;
        this.lib = lib;
        this.setTitle("Registrar libro");
        new TextPrompt("  Título", txtf_tituloLibro);
        new TextPrompt("  Nombre Autor", txtf_nombreAutor); 
        new TextPrompt("  ISBN", txtf_isbn); 
        new TextPrompt("  Editorial", txtf_editorial);
        new TextPrompt("  Lugar de publicación", txtf_lugarPub);
        new TextPrompt("  No. Páginas", txtf_numPaginas);
        new TextPrompt("  No. Libros", txtf_numLibros);
        new TextPrompt("  Año publición", txtf_anoPub);
    }
    
    public RegistrarLibro(StmtSQL cxn) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.cxn = cxn;
        this.setTitle("Registrar libro");
        new TextPrompt("  Título", txtf_tituloLibro);
        new TextPrompt("  Nombre Autor", txtf_nombreAutor); 
        new TextPrompt("  ISBN", txtf_isbn); 
        new TextPrompt("  Editorial", txtf_editorial);
        new TextPrompt("  Lugar de publicación", txtf_lugarPub);
        new TextPrompt("  No. Páginas", txtf_numPaginas);
        new TextPrompt("  No. Libros", txtf_numLibros);
        new TextPrompt("  Año publición", txtf_anoPub);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        main_panelRegistroLibro = new javax.swing.JPanel();
        panel_windowOpRegistroLibro = new javax.swing.JPanel();
        btn_exitRegistrarLibro = new javax.swing.JLabel();
        btn_minimizeRegistrarLibro = new javax.swing.JLabel();
        lbl_titleRegistroLibro = new javax.swing.JLabel();
        panel_formulario = new javax.swing.JPanel();
        line_tituloLibro = new javax.swing.JSeparator();
        txtf_tituloLibro = new javax.swing.JTextField();
        line_nombreAutor = new javax.swing.JSeparator();
        line_numPaginas = new javax.swing.JSeparator();
        txtf_numPaginas = new javax.swing.JTextField();
        line_lugarPub = new javax.swing.JSeparator();
        txtf_lugarPub = new javax.swing.JTextField();
        txtf_nombreAutor = new javax.swing.JTextField();
        line_editorial = new javax.swing.JSeparator();
        txtf_editorial = new javax.swing.JTextField();
        line_isbn = new javax.swing.JSeparator();
        txtf_isbn = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        line_numLibros = new javax.swing.JSeparator();
        txtf_numLibros = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtf_anoPub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(420, 350));

        main_panelRegistroLibro.setBackground(new java.awt.Color(71, 91, 116));
        main_panelRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 350));
        main_panelRegistroLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_windowOpRegistroLibro.setBackground(new java.awt.Color(31, 51, 76));
        panel_windowOpRegistroLibro.setPreferredSize(new java.awt.Dimension(420, 30));
        panel_windowOpRegistroLibro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMouseDragged(evt);
            }
        });
        panel_windowOpRegistroLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_windowOpRegistroLibroMousePressed(evt);
            }
        });

        btn_exitRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitRegistrarLibro.setToolTipText("Cerrar");
        btn_exitRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitRegistrarLibroMouseExited(evt);
            }
        });

        btn_minimizeRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeRegistrarLibro.setToolTipText("Minimizar");
        btn_minimizeRegistrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeRegistrarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeRegistrarLibroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_windowOpRegistroLibroLayout = new javax.swing.GroupLayout(panel_windowOpRegistroLibro);
        panel_windowOpRegistroLibro.setLayout(panel_windowOpRegistroLibroLayout);
        panel_windowOpRegistroLibroLayout.setHorizontalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_windowOpRegistroLibroLayout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(btn_minimizeRegistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exitRegistrarLibro)
                .addGap(86, 86, 86))
        );
        panel_windowOpRegistroLibroLayout.setVerticalGroup(
            panel_windowOpRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_minimizeRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(btn_exitRegistrarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panelRegistroLibro.add(panel_windowOpRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        lbl_titleRegistroLibro.setBackground(new java.awt.Color(51, 71, 96));
        lbl_titleRegistroLibro.setFont(new java.awt.Font("Kristen ITC", 0, 16)); // NOI18N
        lbl_titleRegistroLibro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titleRegistroLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_25px.png"))); // NOI18N
        lbl_titleRegistroLibro.setText("Registro Libro");
        lbl_titleRegistroLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 121, 146), 2, true));
        lbl_titleRegistroLibro.setOpaque(true);
        main_panelRegistroLibro.add(lbl_titleRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 30));

        panel_formulario.setBackground(new java.awt.Color(51, 71, 96));
        panel_formulario.setPreferredSize(new java.awt.Dimension(350, 350));

        line_tituloLibro.setBackground(new java.awt.Color(131, 151, 176));
        line_tituloLibro.setForeground(new java.awt.Color(0, 0, 0));

        txtf_tituloLibro.setBackground(new java.awt.Color(51, 71, 96));
        txtf_tituloLibro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_tituloLibro.setForeground(new java.awt.Color(255, 255, 255));
        txtf_tituloLibro.setBorder(null);
        txtf_tituloLibro.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_tituloLibro.setOpaque(false);
        txtf_tituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_tituloLibroKeyTyped(evt);
            }
        });

        line_nombreAutor.setBackground(new java.awt.Color(131, 151, 176));
        line_nombreAutor.setForeground(new java.awt.Color(0, 0, 0));

        line_numPaginas.setBackground(new java.awt.Color(131, 151, 176));
        line_numPaginas.setForeground(new java.awt.Color(0, 0, 0));

        txtf_numPaginas.setBackground(new java.awt.Color(51, 71, 96));
        txtf_numPaginas.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_numPaginas.setForeground(new java.awt.Color(255, 255, 255));
        txtf_numPaginas.setBorder(null);
        txtf_numPaginas.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_numPaginas.setOpaque(false);
        txtf_numPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_numPaginasKeyTyped(evt);
            }
        });

        line_lugarPub.setBackground(new java.awt.Color(131, 151, 176));
        line_lugarPub.setForeground(new java.awt.Color(0, 0, 0));

        txtf_lugarPub.setBackground(new java.awt.Color(51, 71, 96));
        txtf_lugarPub.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_lugarPub.setForeground(new java.awt.Color(255, 255, 255));
        txtf_lugarPub.setBorder(null);
        txtf_lugarPub.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_lugarPub.setOpaque(false);
        txtf_lugarPub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_lugarPubKeyTyped(evt);
            }
        });

        txtf_nombreAutor.setBackground(new java.awt.Color(51, 71, 96));
        txtf_nombreAutor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_nombreAutor.setForeground(new java.awt.Color(255, 255, 255));
        txtf_nombreAutor.setBorder(null);
        txtf_nombreAutor.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_nombreAutor.setOpaque(false);
        txtf_nombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_nombreAutorKeyTyped(evt);
            }
        });

        line_editorial.setBackground(new java.awt.Color(131, 151, 176));
        line_editorial.setForeground(new java.awt.Color(0, 0, 0));

        txtf_editorial.setBackground(new java.awt.Color(51, 71, 96));
        txtf_editorial.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtf_editorial.setBorder(null);
        txtf_editorial.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_editorial.setOpaque(false);
        txtf_editorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_editorialKeyTyped(evt);
            }
        });

        line_isbn.setBackground(new java.awt.Color(131, 151, 176));
        line_isbn.setForeground(new java.awt.Color(0, 0, 0));

        txtf_isbn.setBackground(new java.awt.Color(51, 71, 96));
        txtf_isbn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_isbn.setForeground(new java.awt.Color(255, 255, 255));
        txtf_isbn.setBorder(null);
        txtf_isbn.setCaretColor(new java.awt.Color(255, 255, 255));
        txtf_isbn.setOpaque(false);
        txtf_isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_isbnKeyTyped(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_17px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_limpiar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_broom_17px.png"))); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        txtf_numLibros.setBackground(new java.awt.Color(51, 71, 96));
        txtf_numLibros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_numLibros.setForeground(new java.awt.Color(255, 255, 255));
        txtf_numLibros.setBorder(null);
        txtf_numLibros.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtf_numLibros.setSelectedTextColor(new java.awt.Color(109, 109, 109));
        txtf_numLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_numLibrosKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_help_14px_1.png"))); // NOI18N
        jLabel1.setToolTipText("Cantidad de libros que desea registrar con los mismos datos.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtf_anoPub.setBackground(new java.awt.Color(51, 71, 96));
        txtf_anoPub.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtf_anoPub.setForeground(new java.awt.Color(255, 255, 255));
        txtf_anoPub.setBorder(null);

        javax.swing.GroupLayout panel_formularioLayout = new javax.swing.GroupLayout(panel_formulario);
        panel_formulario.setLayout(panel_formularioLayout);
        panel_formularioLayout.setHorizontalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_formularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(line_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(line_editorial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_editorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(line_nombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_nombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_lugarPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line_lugarPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(line_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtf_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtf_anoPub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))))
                .addGap(117, 117, 117))
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addComponent(txtf_numLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar))
                    .addComponent(line_numLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_formularioLayout.setVerticalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtf_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line_tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line_nombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(line_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtf_anoPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_limpiar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtf_lugarPub, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line_lugarPub, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtf_numLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(line_numLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        main_panelRegistroLibro.add(panel_formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseClicked
        if(lib!=null)
            lib.setTableData("");
        this.dispose();
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseClicked

    private void btn_exitRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseEntered
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseEntered

    private void btn_exitRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitRegistrarLibroMouseExited
        btn_exitRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitRegistrarLibroMouseExited

    private void btn_minimizeRegistrarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseClicked

    private void btn_minimizeRegistrarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseEntered
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseEntered

    private void btn_minimizeRegistrarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeRegistrarLibroMouseExited
        btn_minimizeRegistrarLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeRegistrarLibroMouseExited

    private void panel_windowOpRegistroLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_windowOpRegistroLibroMousePressed

    private void panel_windowOpRegistroLibroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOpRegistroLibroMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_panel_windowOpRegistroLibroMouseDragged

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txtf_tituloLibro.setText("");
        txtf_nombreAutor.setText("");
        txtf_isbn.setText(""); 
        txtf_editorial.setText("");
        txtf_lugarPub.setText("");
        txtf_numPaginas.setText("");
        txtf_anoPub.setText("");
        txtf_numLibros.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txtf_tituloLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_tituloLibroKeyTyped
        if(txtf_tituloLibro.getText().length() >= 100)
            evt.consume();
    }//GEN-LAST:event_txtf_tituloLibroKeyTyped

    private void txtf_nombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_nombreAutorKeyTyped
        if(txtf_nombreAutor.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtf_nombreAutorKeyTyped

    private void txtf_isbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_isbnKeyTyped
        if(txtf_isbn.getText().length() >= 13)
            evt.consume();
    }//GEN-LAST:event_txtf_isbnKeyTyped

    private void txtf_editorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_editorialKeyTyped
        if(txtf_editorial.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtf_editorialKeyTyped

    private void txtf_numPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_numPaginasKeyTyped
        if(txtf_numPaginas.getText().length() >= 6)
            evt.consume();
    }//GEN-LAST:event_txtf_numPaginasKeyTyped

    private void txtf_lugarPubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_lugarPubKeyTyped
        if(txtf_lugarPub.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtf_lugarPubKeyTyped

    private void txtf_numLibrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_numLibrosKeyTyped
        if(txtf_numLibros.getText().length() >= 6)
            evt.consume();
    }//GEN-LAST:event_txtf_numLibrosKeyTyped
  
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        nLibro[1] = txtf_tituloLibro.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[2] = txtf_nombreAutor.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[3] = txtf_editorial.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[4] = txtf_numPaginas.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[5] = txtf_lugarPub.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[6] = txtf_anoPub.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[7] = txtf_isbn.getText().toLowerCase().replaceAll("^\\s*","").replaceAll("\\s*$","");
        nLibro[8] = txtf_numLibros.getText().replaceAll("^\\s*","").replaceAll("\\s*$","");
        Calendar date = Calendar.getInstance();
        String dia = Integer.toString(date.get(Calendar.DATE));
        String mes = Integer.toString(date.get(Calendar.MONTH)+1);
        String ano = Integer.toString(date.get(Calendar.YEAR));
        nLibro[10] = ano+"-"+mes+"-"+dia;
        try {
            cxn.registrarLibro(nLibro);
            JOptionPane.showMessageDialog(null, "Se ha registrado el libro.", "Codex",1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(), "Codex",1);
        }
        btn_limpiarActionPerformed(null);
    }//GEN-LAST:event_btn_guardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exitRegistrarLibro;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel btn_minimizeRegistrarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_titleRegistroLibro;
    private javax.swing.JSeparator line_editorial;
    private javax.swing.JSeparator line_isbn;
    private javax.swing.JSeparator line_lugarPub;
    private javax.swing.JSeparator line_nombreAutor;
    private javax.swing.JSeparator line_numLibros;
    private javax.swing.JSeparator line_numPaginas;
    private javax.swing.JSeparator line_tituloLibro;
    private javax.swing.JPanel main_panelRegistroLibro;
    private javax.swing.JPanel panel_formulario;
    private javax.swing.JPanel panel_windowOpRegistroLibro;
    private javax.swing.JTextField txtf_anoPub;
    private javax.swing.JTextField txtf_editorial;
    private javax.swing.JTextField txtf_isbn;
    private javax.swing.JTextField txtf_lugarPub;
    private javax.swing.JTextField txtf_nombreAutor;
    private javax.swing.JTextField txtf_numLibros;
    private javax.swing.JTextField txtf_numPaginas;
    private javax.swing.JTextField txtf_tituloLibro;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    String[] nLibro = new String[12];
    StmtSQL cxn;
    Libros lib;
}
