/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.StmtSQL;
import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author fresh-fresh
 */
public class SeleccionLibro extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionLibro
     */
    public SeleccionLibro(StmtSQL cxn, RegistrarPrestamo vrPrestamo) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.cxn = cxn;
        this.vrPrestamo = vrPrestamo;
        this.setTitle("Seleccionar libro");
        new TextPrompt("  Buscar Libro...", txtf_buscadorLibro);
        configTable();
    }
    
    public SeleccionLibro(StmtSQL cxn, ModificarPrestamo vmPrestamo) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(128, 142, 159)));
        this.setIconImage(new ImageIcon(this.getClass().getResource("../icons/icons8_literature_25px_1.png")).getImage());
        this.cxn = cxn;
        this.vmPrestamo = vmPrestamo;
        this.setTitle("Seleccionar libro");
        new TextPrompt("  Buscar Libro...", txtf_buscadorLibro);
        configTable();
    }

    private void configTable(){
        model.addColumn("ID");
        model.addColumn("TITULO");
        model.addColumn("AUTOR");
        model.addColumn("EDITORIAL");
        model.addColumn("PAGINAS");
        model.addColumn("LUGAR_PUBLICACION");
        model.addColumn("FECHA_PUBLICACION");
        model.addColumn("ISBN");
        model.addColumn("EXISTENCIA");
        model.addColumn("DISPONIBILIDAD");
        model.addColumn("FECHA_REGISTRO");
        model.addColumn("FECHA_BAJA");
        table_libros.setModel(model);
        TableColumnModel columnModel = table_libros.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(35);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(110);
        columnModel.getColumn(3).setPreferredWidth(110);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(140);
        columnModel.getColumn(6).setPreferredWidth(140);
        columnModel.getColumn(7).setPreferredWidth(110);
        columnModel.getColumn(8).setPreferredWidth(85);
        columnModel.getColumn(9).setPreferredWidth(110);
        columnModel.getColumn(10).setPreferredWidth(130);
        columnModel.getColumn(11).setPreferredWidth(110);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_windowOptions = new javax.swing.JPanel();
        btn_exitSeleccionLibro = new javax.swing.JLabel();
        btn_minimizeSeleccionLibro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_busqueda_ordenamiento = new javax.swing.JPanel();
        txtf_buscadorLibro = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JLabel();
        cmb_ordenar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_libros = new javax.swing.JTable();
        btn_listo = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 330));

        jPanel1.setBackground(new java.awt.Color(101, 121, 146));

        panel_windowOptions.setBackground(new java.awt.Color(54, 71, 89));
        panel_windowOptions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_windowOptionsMouseDragged(evt);
            }
        });
        panel_windowOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_windowOptionsMousePressed(evt);
            }
        });

        btn_exitSeleccionLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCloseOff.png"))); // NOI18N
        btn_exitSeleccionLibro.setToolTipText("Cerrar");
        btn_exitSeleccionLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exitSeleccionLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitSeleccionLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitSeleccionLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitSeleccionLibroMouseExited(evt);
            }
        });

        btn_minimizeSeleccionLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMinimize.png"))); // NOI18N
        btn_minimizeSeleccionLibro.setToolTipText("Minimizar");
        btn_minimizeSeleccionLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizeSeleccionLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeSeleccionLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeSeleccionLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeSeleccionLibroMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_25px_1.png"))); // NOI18N
        jLabel1.setText("Seleccionar Libro");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_windowOptionsLayout = new javax.swing.GroupLayout(panel_windowOptions);
        panel_windowOptions.setLayout(panel_windowOptionsLayout);
        panel_windowOptionsLayout.setHorizontalGroup(
            panel_windowOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_windowOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_minimizeSeleccionLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exitSeleccionLibro)
                .addContainerGap())
        );
        panel_windowOptionsLayout.setVerticalGroup(
            panel_windowOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_exitSeleccionLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_minimizeSeleccionLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_busqueda_ordenamiento.setBackground(new java.awt.Color(71, 91, 116));

        txtf_buscadorLibro.setBackground(new java.awt.Color(161, 181, 206));
        txtf_buscadorLibro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtf_buscadorLibro.setToolTipText("Buscar por titulo, autor o ISBN");
        txtf_buscadorLibro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtf_buscadorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_buscadorLibroKeyTyped(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px_3.png"))); // NOI18N
        btn_buscar.setToolTipText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarMouseExited(evt);
            }
        });

        cmb_ordenar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        cmb_ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordernar por", "Titulo", "Nombre autor", "ISBN", "No.paginas." }));

        javax.swing.GroupLayout panel_busqueda_ordenamientoLayout = new javax.swing.GroupLayout(panel_busqueda_ordenamiento);
        panel_busqueda_ordenamiento.setLayout(panel_busqueda_ordenamientoLayout);
        panel_busqueda_ordenamientoLayout.setHorizontalGroup(
            panel_busqueda_ordenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busqueda_ordenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtf_buscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_busqueda_ordenamientoLayout.setVerticalGroup(
            panel_busqueda_ordenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busqueda_ordenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_busqueda_ordenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_ordenar)
                    .addComponent(txtf_buscadorLibro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_busqueda_ordenamientoLayout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        table_libros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        table_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_libros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table_libros);

        btn_listo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_listo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ok_22px.png"))); // NOI18N
        btn_listo.setText("Listo");
        btn_listo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_22px.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_windowOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(panel_busqueda_ordenamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_windowOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_busqueda_ordenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_listo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitSeleccionLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitSeleccionLibroMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_exitSeleccionLibroMouseClicked

    private void btn_exitSeleccionLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitSeleccionLibroMouseEntered
        btn_exitSeleccionLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconClose.png")));
    }//GEN-LAST:event_btn_exitSeleccionLibroMouseEntered

    private void btn_exitSeleccionLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitSeleccionLibroMouseExited
        btn_exitSeleccionLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconCloseOff.png")));
    }//GEN-LAST:event_btn_exitSeleccionLibroMouseExited

    private void btn_minimizeSeleccionLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeSeleccionLibroMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeSeleccionLibroMouseClicked

    private void btn_minimizeSeleccionLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeSeleccionLibroMouseEntered
        btn_minimizeSeleccionLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimizeOn.png")));
    }//GEN-LAST:event_btn_minimizeSeleccionLibroMouseEntered

    private void btn_minimizeSeleccionLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeSeleccionLibroMouseExited
        btn_minimizeSeleccionLibro.setIcon(new ImageIcon(this.getClass().getResource("../icons/iconMinimize.png")));
    }//GEN-LAST:event_btn_minimizeSeleccionLibroMouseExited

    private void btn_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseEntered
        btn_buscar.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_1.png")));
    }//GEN-LAST:event_btn_buscarMouseEntered

    private void btn_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseExited
        btn_buscar.setIcon(new ImageIcon(this.getClass().getResource("../icons/icons8_search_25px_3.png")));
    }//GEN-LAST:event_btn_buscarMouseExited

    private void panel_windowOptionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOptionsMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_windowOptionsMousePressed

    private void panel_windowOptionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_windowOptionsMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_panel_windowOptionsMouseDragged

    private void setTableData(String texto){
        model.setRowCount(0);
        try {
            ResultSet rs = cxn.consultaLibros(texto+"%");
            while(rs.next()){
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                data[7] = rs.getString(8);
                data[8] = rs.getString(9);
                data[9] = rs.getString(10);
                data[10] = rs.getString(11);
                data[11] = rs.getString(12);
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.out);
        }
    }
    
    private void txtf_buscadorLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscadorLibroKeyTyped
        String textoBuscador = txtf_buscadorLibro.getText();
        setTableData(textoBuscador);
        if(txtf_buscadorLibro.getText().length() >= 150)
            evt.consume();
    }//GEN-LAST:event_txtf_buscadorLibroKeyTyped

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void btn_listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listoActionPerformed
        int sRow = table_libros.getSelectedRow();
        if(sRow<0)
            JOptionPane.showMessageDialog(null, "ERROR: selecciona un miembro de la tabla", "Codex", 2);
        else{
            if(vrPrestamo!=null){
                vrPrestamo.sLibro = (String) table_libros.getValueAt(sRow, 0);
                String nLibro = (String) table_libros.getValueAt(sRow, 1);
                vrPrestamo.establecerLibro(nLibro);
            }else if(vmPrestamo!=null){
                vmPrestamo.sLibro = (String) table_libros.getValueAt(sRow, 0);
                String nLibro = (String) table_libros.getValueAt(sRow, 1);
                vmPrestamo.establecerLibro(nLibro);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btn_listoActionPerformed
                                                                                                    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel btn_exitSeleccionLibro;
    private javax.swing.JButton btn_listo;
    private javax.swing.JLabel btn_minimizeSeleccionLibro;
    private javax.swing.JComboBox<String> cmb_ordenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_busqueda_ordenamiento;
    private javax.swing.JPanel panel_windowOptions;
    private javax.swing.JTable table_libros;
    private javax.swing.JTextField txtf_buscadorLibro;
    // End of variables declaration//GEN-END:variables
    private int x;
    private int y;
    StmtSQL cxn;
    RegistrarPrestamo vrPrestamo;
    ModificarPrestamo vmPrestamo;
    String[] data = new String[12];
    DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
}
